// TaleemPK static data — auto-extracted from index.html
const T = {
  en: {
    nav_universities:'Universities', nav_compare:'Compare', nav_how:'How It Works', nav_cta:'View Universities',
    hero_badge:"Pakistan's #1 Education Comparison Platform",
    hero_h1:'Choose the Right <span>University</span> <span class="hero-dash">—</span><br>All Info in One Place',
    hero_urdu:'فیس، میرٹ، پروگرام — سب کچھ ایک جگہ',
    hero_sub:'Data on 218 HEC-recognized universities in Pakistan — fees, merit, programs. Compare side-by-side and decide your future.',
    hero_search_placeholder:'Search university or program…',
    hero_search_btn:'🔍 Search',
    stat1_label:'Top Universities', stat2_label:'Programs Listed', stat3_label:'Students Helped', stat4_label:'Cities Covered',
    filter_label:'Filter:', filter_all:'All (218)', filter_public:'🏛️ Public', filter_private:'🏢 Private',
    filter_engineering:'⚙️ Engineering', filter_medical:'🏥 Medical', filter_business:'💼 Business',
    filter_federal:'🏙️ Federal', filter_punjab:'🌾 Punjab', filter_sindh:'🌊 Sindh',
    filter_kpk:'🏔️ KPK', filter_balochistan:'🏜️ Balochistan', filter_ajk:'🏞️ AJK', filter_gb:'⛰️ GB',
    fee_label:'FEE/SEMESTER', merit_label:'MERIT / ENTRY',
    btn_compare:'+ Compare', btn_added:'✓ Added', btn_details:'Details →',
    tag_public:'🏛️ Public', tag_private:'🏢 Private',
    hiw_label:'Simple Process', hiw_title:'Make the Right<br>Decision in 3 Steps',
    hiw_sub:'Comprehensive university data for Pakistan — all in one place',
    step1_num:'STEP 01', step1_title:'Search', step1_desc:'Find universities by city, program, or fee range. 218 HEC-recognized institutions listed.',
    step2_num:'STEP 02', step2_title:'Compare', step2_desc:'Compare 2–3 universities side-by-side — fees, merit, programs, and location all at once.',
    step3_num:'STEP 03', step3_title:'Decide', step3_desc:'Make a confident decision with complete information. No guessing, no confusion.',
    step4_num:'COMING SOON', step4_title:'AI Predictor', step4_desc:'Enter your aggregate — AI will predict your admission chances at each university.',
    compare_bar_title:'⚖️ Compare List:', compare_bar_btn:'Compare Now →',
    footer_tagline:"Pakistan's #1 Education Comparison Platform",
    footer_link1:'Universities', footer_link2:'Compare', footer_link3:'Admission Calendar', footer_link4:'Scholarships', footer_link5:'About',
    footer_copy:'© 2026 TaleemPK — All rights reserved | Karachi, Pakistan',
    detail_fee:'💰 Fee Per Semester', detail_entry:'📝 Entry Test', detail_merit:'🏆 Merit Required',
    detail_seats:'👥 Seats Per Year', detail_scholarships:'🎓 Scholarships', detail_hostel:'🏠 Hostel',
    detail_programs:'📚 Programs Offered', detail_highlights:'✨ Highlights',
    detail_website_btn:'🌐 Visit Official Website →', detail_est:'Est.',
    compare_modal_label:'Side-by-Side Comparison', compare_modal_title:'University Comparison',
    compare_tip:'💡 The <strong>green</strong> highlight shows the most affordable fee option. The right choice depends on your program, merit, and budget.',
    row_university:'University', row_city:'City', row_type:'Type', row_fee:'Fee/Semester',
    row_entry:'Entry Test', row_merit:'Merit Required', row_programs:'Top Programs',
    row_seats:'Seats/Year', row_scholarships:'Scholarships', row_hostel:'Hostel',
    row_established:'Established', row_website:'Website',
    alert_max:'You can compare a maximum of 3 universities!',
    alert_min:'Please select at least 2 universities to compare!',
    showing: c => `Showing <span>${c}</span> universities`,
  },
};
const PROVINCE_MAP = {
  1:'Federal',2:'Punjab',3:'Punjab',4:'Sindh',5:'Federal',
  6:'Federal',7:'Federal',8:'KPK',9:'Federal',10:'Sindh',
  11:'Punjab',12:'Sindh',13:'Sindh',14:'Federal',15:'Federal',
  16:'Punjab',17:'Sindh',18:'Punjab',19:'Sindh',20:'Punjab',
  21:'Federal',22:'Punjab',23:'Federal',24:'Punjab',25:'Sindh',
  26:'Punjab',27:'Punjab',28:'Federal',29:'KPK'
};
const WEBSITE_MAP = {
  // Federal
  31:'ndu.edu.pk',32:'aiou.edu.pk',33:'vu.edu.pk',34:'cust.edu.pk',
  35:'riphah.edu.pk',36:'fuuast.edu.pk',37:'fui.edu.pk',38:'pide.org.pk',
  39:'shifa.edu.pk',40:'szabmu.edu.pk',41:'nutech.edu.pk',42:'nsu.edu.pk',
  43:'case.edu.pk',44:'ibadat.edu.pk',45:'myu.edu.pk',
  // Punjab - Lahore
  46:'lcwu.edu.pk',47:'fjmu.edu.pk',48:'kemu.edu.pk',49:'uvas.edu.pk',
  50:'kinnaird.edu.pk',51:'umt.edu.pk',52:'uol.edu.pk',53:'bnu.edu.pk',
  54:'minhaj.edu.pk',55:'superior.edu.pk',56:'ue.edu.pk',57:'hajvery.edu.pk',
  58:'pifd.edu.pk',59:'lahoreschoolofeconomics.edu.pk',60:'lgu.edu.pk',
  61:'uohe.edu.pk',62:'ncbae.edu.pk',63:'southasia.edu.pk',64:'imscienceslahore.edu.pk',
  65:'iac.edu.pk',66:'leads.edu.pk',67:'qarshi.edu.pk',68:'nur.edu.pk',
  // Punjab - Rawalpindi / Attock
  69:'uaar.edu.pk',70:'fjwu.edu.pk',71:'rmu.edu.pk',72:'nums.edu.pk',73:'rwu.edu.pk',
  // Punjab - Taxila / Wah
  74:'hitecuni.edu.pk',112:'uow.edu.pk',113:'putr.edu.pk',
  // Punjab - Faisalabad
  75:'uaf.edu.pk',76:'gcuf.edu.pk',77:'ntu.edu.pk',78:'fmu.edu.pk',
  79:'gcwuf.edu.pk',80:'tuf.edu.pk',
  // Punjab - Bahawalpur
  81:'iub.edu.pk',82:'gscwu.edu.pk',83:'cuvas.edu.pk',
  // Punjab - Multan
  84:'wum.edu.pk',85:'usp.edu.pk',86:'nmu.edu.pk',87:'nfc-iet.edu.pk',
  88:'mnsuam.edu.pk',89:'mnsuet.edu.pk',90:'timesinstitute.edu.pk',91:'emerson.edu.pk',
  // Punjab - Sargodha / Gujranwala / Sialkot / Mianwali
  92:'uos.edu.pk',93:'gift.edu.pk',94:'uog.edu.pk',95:'uskt.edu.pk',
  96:'gcwus.edu.pk',97:'namal.edu.pk',98:'umianwali.edu.pk',99:'uookara.edu.pk',
  100:'uosaghiwal.edu.pk',101:'ujhang.edu.pk',102:'ghaziuniversity.edu.pk',
  103:'kfueit.edu.pk',104:'unarowal.edu.pk',105:'uochakwal.edu.pk',
  106:'ulayyah.edu.pk',107:'kum.edu.pk',108:'thaluniversity.edu.pk',
  109:'alqadiruniversity.edu.pk',110:'bgnu.edu.pk',111:'ptutt.edu.pk',
  // Sindh - Karachi
  114:'uok.edu.pk',115:'ssuet.edu.pk',116:'ivs.edu.pk',117:'hamdard.edu.pk',
  118:'jsmu.edu.pk',119:'baqai.edu.pk',120:'dsu.edu.pk',121:'zu.edu.pk',
  122:'iobm.edu.pk',123:'iqra.edu.pk',124:'duet.edu.pk',125:'greenwich.edu.pk',
  126:'jinnah.edu.pk',127:'kiet.edu.pk',128:'smiu.edu.pk',129:'juw.edu.pk',
  130:'dadabhoy.edu.pk',131:'ilmauniversity.edu.pk',132:'indus.edu.pk',
  133:'ksbl.edu.pk',134:'shu.edu.pk',135:'sbbcu.edu.pk',136:'cuhs.edu.pk',
  137:'newports.edu.pk',138:'pna.edu.pk',139:'kinpoe.edu.pk',140:'malir.edu.pk',
  141:'bbsul.edu.pk',
  // Sindh - Interior
  142:'usindh.edu.pk',143:'lumhs.edu.pk',144:'gcuh.edu.pk',145:'isra.edu.pk',
  146:'sau.edu.pk',147:'iba-suk.edu.pk',148:'salu.edu.pk',149:'quest.edu.pk',
  150:'sbbu.edu.pk',151:'pumhs.edu.pk',152:'sbbuvs.edu.pk',153:'sbbmul.edu.pk',
  154:'usms.edu.pk',155:'shaikhayaz.edu.pk',156:'aror.edu.pk',157:'bnbwu.edu.pk',
  158:'sabsua.edu.pk',
  // KPK - Peshawar
  159:'icp.edu.pk',160:'uetpeshawar.edu.pk',161:'kmu.edu.pk',162:'imsciences.edu.pk',
  163:'sbbwup.edu.pk',164:'cecos.edu.pk',165:'gandhara.edu.pk',166:'sarhad.edu.pk',
  167:'cityuniversity.edu.pk',168:'abasyn.edu.pk',
  // KPK - DI Khan / Gomal
  169:'qurtuba.edu.pk',170:'gu.edu.pk',
  // KPK - Agriculture / Malakand / Swat / Hazara
  171:'aup.edu.pk',172:'uom.edu.pk',173:'uswat.edu.pk',174:'uswabi.edu.pk',
  175:'hu.edu.pk',176:'aust.edu.pk',177:'kust.edu.pk',178:'uoh.edu.pk',
  // KPK - Mardan / Charsadda / Bannu / Others
  179:'awkum.edu.pk',180:'wumardan.edu.pk',181:'uetmardan.edu.pk',182:'bkuc.edu.pk',
  183:'ustb.edu.pk',184:'wuswabi.edu.pk',185:'kkkuk.edu.pk',186:'sbbush.edu.pk',
  187:'ubuner.edu.pk',188:'utn.edu.pk',189:'fatauniversity.edu.pk',
  190:'uochitral.edu.pk',191:'uolm.edu.pk',192:'uodir.edu.pk',193:'uoshangla.edu.pk',
  194:'paf-iast.edu.pk',195:'inu.edu.pk',196:'northern.edu.pk',197:'uoadik.edu.pk',
  // Balochistan
  198:'uob.edu.pk',199:'bumhs.edu.pk',200:'buitms.edu.pk',201:'sbkwu.edu.pk',
  202:'uot.edu.pk',203:'uogwadar.edu.pk',204:'umakran.edu.pk',205:'buetk.edu.pk',
  206:'luawms.edu.pk',207:'uolor.edu.pk',208:'mckru.edu.pk',209:'alhamd.edu.pk',
  // AJK
  210:'must.edu.pk',211:'ajku.edu.pk',212:'upr.edu.pk',213:'al-khair.edu.pk',
  214:'miuazad.edu.pk',215:'wuajkbagh.edu.pk',216:'uokotli.edu.pk',
  // Gilgit-Baltistan
  217:'kiu.edu.pk',218:'baltistanuniversity.edu.pk'
};
const DATA_UPDATES = {
  // ── FEDERAL ──
  32:{ fee:'Rs. 5–15K/sem', feeNum:10000, merit:'Open Enrollment', entry:'No entry test',
    programs:['BA','BSc','B.Ed','BBA','MBA','MA','MSc','MPhil','PhD'],
    description:'Allama Iqbal Open University (AIOU) is Pakistan\'s largest distance-learning institution, founded in 1974. With over 1.3 million enrolled students, it offers flexible education from matric to PhD level across all four provinces.',
    highlights:['1.3M+ Students','Distance Learning','Countrywide Reach','Affordable Fees'],
    scholarships:'Need-based & merit scholarships available', hostel:'Not applicable (distance learning)' },
  33:{ fee:'Rs. 8–20K/sem', feeNum:14000, merit:'Merit-based (previous grades)', entry:'No entry test',
    programs:['BS CS','BS IT','BBA','MBA','BS Math','BS English','BS Commerce'],
    description:'Virtual University of Pakistan (VU) is the country\'s first public online university, established in 2002. It delivers HEC-recognized degrees entirely through e-learning, making quality education accessible from anywhere in Pakistan.',
    highlights:['100% Online','Affordable','HEC Recognized','No Entry Test'],
    scholarships:'Need-based scholarships via HEC', hostel:'Not applicable (online university)' },
  34:{ fee:'Rs. 60–100K/sem', feeNum:80000, merit:'70%+ in FSc', entry:'CUST Entry Test',
    programs:['BS CS','BS SE','BS EE','BBA','MBA','BS Telecom'],
    description:'Capital University of Science & Technology (CUST) is a private HEC-recognized university in Islamabad, known for strong engineering and IT programs with modern labs and industry linkages.',
    highlights:['Engineering Focus','Modern Labs','Industry Links','Islamabad Campus'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  35:{ fee:'Rs. 80–150K/sem', feeNum:115000, merit:'65%+ in FSc', entry:'Riphah Entry Test',
    programs:['MBBS','DPT','Pharmacy','BS Nursing','BBA','BS CS','Islamic Studies'],
    description:'Riphah International University is a private university in Islamabad offering programs in medical, engineering, and Islamic studies. It is known for integrating Islamic values with modern education.',
    highlights:['Medical & Islamic Studies','Modern Facilities','Multiple Campuses','HEC W-Category'],
    scholarships:'Merit, need-based & Islamic studies scholarships', hostel:'Separate hostels for males & females' },
  41:{ fee:'Rs. 40–70K/sem', feeNum:55000, merit:'60%+ in FSc Pre-Engineering', entry:'NUTECH Entry Test',
    programs:['BS Civil Eng','BS Electrical Eng','BS Mechanical Eng','BS CS','BS SE'],
    description:'National University of Technology (NUTECH) is a public university in Islamabad established in 2018, offering engineering and technology programs with strong industrial collaboration.',
    highlights:['Public University','Engineering Focus','Industry Collaboration','New Campus'],
    scholarships:'HEC need-based & merit scholarships', hostel:'Available on campus' },
  72:{ fee:'Rs. 60–120K/sem', feeNum:90000, merit:'Army/NUMS Merit List', entry:'NUMS Entry Test / MDCAT',
    programs:['MBBS','BDS','Doctor of Pharmacy','DPT','BS Nursing','Allied Health'],
    description:'National University of Medical Sciences (NUMS) Rawalpindi is a military-affiliated medical university. It is ranked among Pakistan\'s top medical institutions with state-of-the-art facilities and teaching hospitals.',
    highlights:['Military Affiliation','Top Medical University','Teaching Hospitals','State-of-art Labs'],
    scholarships:'Military & merit-based scholarships', hostel:'Well-equipped hostels available' },

  // ── PUNJAB – LAHORE ──
  46:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'60%+ in Intermediate', entry:'LCWU Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS IT','BS Education','BS Fashion Design','MA','MSc'],
    description:'Lahore College for Women University (LCWU) is one of Pakistan\'s oldest and most prestigious women\'s universities, founded in 1922. It offers a wide range of undergraduate and postgraduate programs in a safe and academic environment.',
    highlights:['Women\'s University','100+ Years Heritage','Large Campus','Affordable Fees'],
    scholarships:'Merit, need-based & provincial scholarships', hostel:'On-campus hostel available' },
  47:{ fee:'Rs. 50–80K/sem', feeNum:65000, merit:'85%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BDS','DPT','Allied Health Sciences'],
    description:'Fatima Jinnah Medical University (FJMU) Lahore, formerly Fatima Jinnah Medical College, is one of the oldest and most respected women\'s medical colleges in Pakistan, established in 1948.',
    highlights:['Top Medical College','Women\'s University','150+ Years Heritage','Teaching Hospital'],
    scholarships:'Government & merit-based scholarships', hostel:'On-campus hostel for females' },
  48:{ fee:'Rs. 60–100K/sem', feeNum:80000, merit:'85%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BDS','DPT','Allied Health Sciences','Doctor of Pharmacy'],
    description:'King Edward Medical University (KEMU) Lahore is one of the most prestigious medical universities in South Asia, established in 1860. Affiliated with Mayo Hospital, it consistently produces top-ranking doctors.',
    highlights:['165+ Years Heritage','Top Ranking Medical','Affiliated Mayo Hospital','Highly Competitive'],
    scholarships:'Government scholarships & need-based aid', hostel:'Separate hostels for males & females' },
  49:{ fee:'Rs. 25–45K/sem', feeNum:35000, merit:'60%+ in FSc (Pre-Medical)', entry:'UVAS Entry Test',
    programs:['DVM','BS Animal Sciences','BS Food Sciences','BS Bioinformatics','BS Zoology','MPhil','PhD'],
    description:'University of Veterinary & Animal Sciences (UVAS) Lahore is a leading public institution for veterinary, animal, and food sciences in Pakistan, established in 1882. It is the premier institution for DVM programs in Punjab.',
    highlights:['Pakistan\'s Top Vet University','140+ Years Heritage','Research Excellence','Teaching Hospitals'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  50:{ fee:'Rs. 30–60K/sem', feeNum:45000, merit:'60%+ in Intermediate', entry:'Kinnaird Entry Test',
    programs:['BS Sciences','BS Social Sciences','BS Business','BS Arts','MA','MSc'],
    description:'Kinnaird College for Women University Lahore is a prestigious private women\'s institution, founded in 1913 by the Church of Scotland. It is one of Pakistan\'s most respected colleges for liberal arts and sciences.',
    highlights:['Women\'s University','110+ Years Heritage','International Affiliation','Lahore Campus'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  51:{ fee:'Rs. 80–150K/sem', feeNum:115000, merit:'65%+ in FSc', entry:'UMT Entry Test',
    programs:['BBA','MBA','BS CS','BS SE','BS EE','BS Civil Eng','BS Architecture','BS Law'],
    description:'University of Management & Technology (UMT) Lahore is a leading private university known for strong business and engineering programs, industry partnerships, and modern research facilities.',
    highlights:['Business & Engineering','Industry Links','Modern Facilities','Multiple Programs'],
    scholarships:'Merit, need-based & departmental scholarships', hostel:'On-campus hostel available' },
  52:{ fee:'Rs. 60–120K/sem', feeNum:90000, merit:'60%+ in FSc', entry:'UOL Entry Test',
    programs:['MBBS','BDS','BS Engineering','BBA','MBA','BS CS','BS Nursing','BS Allied Health'],
    description:'University of Lahore (UOL) is a large private university offering diverse programs including medical, engineering, and business. It has multiple campuses across Pakistan.',
    highlights:['Diverse Programs','Medical College','Multiple Campuses','Large University'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  55:{ fee:'Rs. 50–100K/sem', feeNum:75000, merit:'60%+ in Intermediate', entry:'Superior Entry Test',
    programs:['BBA','MBA','BS CS','BS SE','BS EE','BS Civil','BS Law','BS Psychology'],
    description:'Superior University Lahore is a well-known private university offering programs in business, engineering, IT, and social sciences with modern facilities and strong alumni network.',
    highlights:['Modern Campus','Strong Alumni','Multiple Programs','Industry Connections'],
    scholarships:'Merit & sports scholarships', hostel:'On-campus hostel available' },
  59:{ fee:'Rs. 30–65K/sem', feeNum:47000, merit:'65%+ in Intermediate', entry:'LSE Entry Test',
    programs:['BS Economics','BBA','MBA','BS Finance','BS Accounting','MA Economics','MPhil'],
    description:'Lahore School of Economics (LSE) is a public sector institution established in 1997, recognized as one of Pakistan\'s leading centers for economics and business education with strong research output.',
    highlights:['Economics Focused','Research Excellence','Lahore Campus','Public Sector'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },

  // ── PUNJAB – RAWALPINDI / ATTOCK ──
  69:{ fee:'Rs. 20–40K/sem', feeNum:30000, merit:'55%+ in FSc', entry:'PMAS-AAUR Entry Test',
    programs:['BS Agriculture','BS Horticulture','BS Food Tech','BS IT','BS Engineering','DVM','MPhil','PhD'],
    description:'Pir Mehr Ali Shah Arid Agriculture University (PMAS-AAUR) Rawalpindi is a public agriculture university established in 1970, specializing in arid zone agriculture, water conservation, and rural development.',
    highlights:['Agriculture Specialist','Research Excellence','Arid Zone Focus','Public University'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  70:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'FJWU Entry Test',
    programs:['BS Sciences','BS Social Sciences','BS IT','BS Business','BS Education','MA','MSc'],
    description:'Fatima Jinnah Women University (FJWU) Rawalpindi is a public women\'s university established in 1998, named after the Mother of the Nation. It provides quality higher education to women across Rawalpindi and surrounding areas.',
    highlights:['Women\'s University','Public Sector','Rawalpindi Campus','Affordable Fees'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  71:{ fee:'Rs. 50–80K/sem', feeNum:65000, merit:'80%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BS Nursing','DPT','Allied Health Sciences'],
    description:'Rawalpindi Medical University (RMU), formerly Rawalpindi Medical College, is one of Pakistan\'s oldest medical institutions established in 1974. It is affiliated with Holy Family Hospital and Benazir Bhutto Hospital.',
    highlights:['Public Medical University','Teaching Hospitals','Rawalpindi Campus','Competitive Merit'],
    scholarships:'Government & merit-based scholarships', hostel:'Separate hostels available' },

  // ── PUNJAB – FAISALABAD ──
  75:{ fee:'Rs. 20–40K/sem', feeNum:30000, merit:'55%+ in FSc', entry:'UAF Entry Test',
    programs:['BS Agriculture','DVM','BS Food Sciences','BS Horticulture','BS Agri Engineering','MPhil','PhD'],
    description:'University of Agriculture Faisalabad (UAF) is one of Pakistan\'s top agricultural universities, established in 1906. It is a leading research institution in food security, crop sciences, and veterinary medicine with nine faculties.',
    highlights:['120+ Years Heritage','Top Agriculture Uni','9 Faculties','Research Excellence'],
    scholarships:'Merit, need-based & HEC scholarships', hostel:'Well-equipped hostels available' },
  76:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'GCUF Entry Test',
    programs:['BS Sciences','BS Commerce','BS Arts','BS IT','BS Engineering','MA','MSc','MPhil','PhD'],
    description:'Government College University Faisalabad (GCUF) is a historic public university, tracing its origins to 1897. It offers a wide range of programs across sciences, humanities, and engineering with affordable public sector fees.',
    highlights:['125+ Years Heritage','Affordable Fees','Public University','Multiple Programs'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  77:{ fee:'Rs. 25–50K/sem', feeNum:37000, merit:'60%+ in FSc', entry:'NTU Entry Test / NET',
    programs:['BS Textile Engineering','BS Textile Design','BS Fashion Design','BS Textile Management','MPhil','PhD'],
    description:'National Textile University (NTU) Faisalabad is Pakistan\'s only specialized textile university, established in 1959. It is the country\'s premier institution for textile engineering, design, and management education.',
    highlights:['Pakistan\'s Only Textile Uni','Specialized Programs','Industry Links','Research Excellence'],
    scholarships:'Merit & industry scholarships', hostel:'On-campus hostel available' },
  81:{ fee:'Rs. 15–35K/sem', feeNum:25000, merit:'55%+ in Intermediate', entry:'IUB Entry Test / NTS',
    programs:['BS Engineering','BS Sciences','BS Commerce','Islamic Studies','BS IT','BS Social Sciences','LLB','MPhil','PhD'],
    description:'Islamia University of Bahawalpur (IUB) is one of Pakistan\'s oldest universities, founded in 1925. It has a rich heritage combining Islamic education with modern sciences, and serves thousands of students from southern Punjab.',
    highlights:['100+ Years Heritage','Islamic Heritage','Southern Punjab','Multiple Programs'],
    scholarships:'Merit, need-based & religious scholarships', hostel:'On-campus hostel available' },

  // ── PUNJAB – OTHERS ──
  91:{ fee:'Rs. 15–25K/sem', feeNum:20000, merit:'55%+ in Intermediate', entry:'NTS / Emerson Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS Education','MA','MSc'],
    description:'Emerson University Multan, formerly Emerson College, is a historic public institution established in 1920. Named after a British education commissioner, it offers diverse undergraduate and graduate programs in Multan.',
    highlights:['100+ Years Heritage','Public University','Multan Campus','Affordable Fees'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  92:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'UOS Entry Test',
    programs:['BS Sciences','BS Agriculture','BS Pharmacy','BS Engineering','BS IT','BS Social Sciences','LLB','MPhil','PhD'],
    description:'University of Sargodha (UOS) is a comprehensive public university with 216+ degree programs across 8 faculties and 3 campuses. It serves students from Sargodha, Bhakkar, Mianwali, and Khushab districts.',
    highlights:['216+ Programs','3 Campuses','Public University','Research Focus'],
    scholarships:'Merit & need-based scholarships', hostel:'Separate hostels available' },
  94:{ fee:'Rs. 15–35K/sem', feeNum:25000, merit:'55%+ in Intermediate', entry:'UOG Entry Test',
    programs:['BS Engineering','BS IT','BS Sciences','BS Arts','BS Business','BS Architecture','MPhil','PhD'],
    description:'University of Gujrat (UOG) is a public university established in 2004, offering 120+ degree programs across 7 faculties. With 16,000+ students and a modern campus, it is one of Punjab\'s fastest growing universities.',
    highlights:['120+ Programs','16K+ Students','Modern Campus','Public University'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  97:{ fee:'Rs. 50–100K/sem', feeNum:75000, merit:'70%+ in FSc', entry:'Namal NAT / Entry Test',
    programs:['BS CS','BS SE','BS Electrical Eng','BS Business Analytics','BS Economics','BBA'],
    description:'Namal University Mianwali is a unique private university affiliated with the University of Bradford (UK), founded by Imran Khan in 2008. It offers internationally recognized degrees with a focus on STEM and business in a modern campus setting.',
    highlights:['Bradford UK Affiliation','International Degrees','Modern Campus','STEM Focus'],
    scholarships:'Generous need-based & merit scholarships (many full scholarships)', hostel:'On-campus hostel available' },
  103:{ fee:'Rs. 25–50K/sem', feeNum:37000, merit:'60%+ in FSc Pre-Engineering', entry:'ETEA / KFUEIT Test',
    programs:['BS CS','BS SE','BS EE','BS Civil Eng','BS Mechanical Eng','BS IT','BBA'],
    description:'Khawaja Fareed University of Engineering & IT (KFUEIT) Rahim Yar Khan is a public engineering university established in 2014 to serve southern Punjab. It offers modern engineering programs with focus on regional development.',
    highlights:['Engineering Focused','Southern Punjab','Public University','Modern Campus'],
    scholarships:'HEC & merit-based scholarships', hostel:'On-campus hostel available' },

  // ── SINDH – KARACHI ──
  114:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'55%+ in Intermediate', entry:'KU Entry Test',
    programs:['BS Sciences','BS Social Sciences','BS Pharmacy','BS Business','LLB','BS IT','Mass Communication','MPhil','PhD'],
    description:'University of Karachi (KU) is Pakistan\'s largest university by enrollment, founded in 1951. It is a premier public institution offering diverse programs across natural sciences, social sciences, pharmacy, and business in the heart of Karachi.',
    highlights:['Pakistan\'s Largest Uni','Public Sector','Founded 1951','70+ Departments'],
    scholarships:'Merit, need-based & government scholarships', hostel:'Separate hostels available' },
  115:{ fee:'Rs. 40–70K/sem', feeNum:55000, merit:'60%+ in FSc', entry:'SSUET Entry Test',
    programs:['BS CS','BS SE','BS EE','BS Telecom','BS Civil Eng','BS Mechanical Eng','BBA'],
    description:'Sir Syed University of Engineering & Technology (SSUET) Karachi is a private engineering university established in 1993, affiliated with the Sir Syed Memorial Society. It is one of Karachi\'s leading engineering institutions.',
    highlights:['Engineering Focus','Sir Syed Heritage','Karachi Campus','Industry Links'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  117:{ fee:'Rs. 80–150K/sem', feeNum:115000, merit:'65%+ in FSc', entry:'Hamdard Entry Test',
    programs:['MBBS','BDS','DPT','Doctor of Pharmacy','BS Eastern Medicine','BS Engineering','BBA'],
    description:'Hamdard University Karachi is a private university founded in 1991 by Hamdard Foundation, known for integrating modern medicine with Eastern/Unani medicine. It operates multiple teaching hospitals and research centers.',
    highlights:['Unani Medicine Pioneer','Teaching Hospitals','Multiple Programs','Research Focus'],
    scholarships:'Hamdard Foundation scholarships', hostel:'On-campus hostel available' },
  118:{ fee:'Rs. 50–80K/sem', feeNum:65000, merit:'80%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BDS','DPT','BS Nursing','Allied Health Sciences'],
    description:'Jinnah Sindh Medical University (JSMU) Karachi, formerly Dow Medical College Karachi campus, is one of Sindh\'s leading public medical universities. It is affiliated with multiple teaching hospitals across Karachi.',
    highlights:['Public Medical','Teaching Hospitals','Karachi Campus','Competitive Merit'],
    scholarships:'Government & merit-based scholarships', hostel:'Separate hostels available' },
  121:{ fee:'Rs. 100–200K/sem', feeNum:150000, merit:'80%+ aggregate (MDCAT)', entry:'MDCAT / Ziauddin Test',
    programs:['MBBS','BDS','Doctor of Pharmacy','DPT','BS Nursing','BS Allied Health','MBA Health Management'],
    description:'Ziauddin University Karachi is one of Pakistan\'s premier private medical universities, established in 1995. Known for world-class medical education and research, it operates multiple state-of-the-art teaching hospitals.',
    highlights:['Premium Medical Uni','State-of-art Hospitals','Research Excellence','International Standards'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  122:{ fee:'Rs. 70–120K/sem', feeNum:95000, merit:'65%+ in Intermediate', entry:'IoBM Entry Test',
    programs:['BBA','MBA','BS Finance','BS Marketing','BS Accounting','BS CS','MPA','Executive MBA'],
    description:'Institute of Business Management (IoBM) Karachi is one of Pakistan\'s top business schools, offering AACSB-accredited programs. Known for strong industry connections and career placement, it is a preferred choice for business education.',
    highlights:['Top Business School','AACSB Accredited','Industry Connections','Career Placement'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  123:{ fee:'Rs. 60–120K/sem', feeNum:90000, merit:'60%+ in Intermediate', entry:'Iqra University Test',
    programs:['BBA','MBA','BS CS','BS SE','BS Engineering','BS Media Studies','BS Education'],
    description:'Iqra University Karachi is a private university established in 1998 with campuses in Karachi, Islamabad, and Peshawar. It is known for business and IT programs with strong industry linkages.',
    highlights:['Multiple Campuses','Business & IT Focus','Industry Links','Modern Facilities'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  124:{ fee:'Rs. 25–50K/sem', feeNum:37000, merit:'60%+ in FSc Pre-Engineering', entry:'DUET Entry Test',
    programs:['BS Civil Eng','BS Electrical Eng','BS Mechanical Eng','BS Industrial Eng','BS CS'],
    description:'Dawood University of Engineering & Technology (DUET) Karachi is a public engineering university established in 1962. One of Karachi\'s oldest engineering institutions, it produces skilled engineers for Pakistan\'s industrial sector.',
    highlights:['Public Engineering Uni','60+ Years Heritage','Karachi Campus','Industry Ties'],
    scholarships:'Government & merit scholarships', hostel:'On-campus hostel available' },

  // ── SINDH – INTERIOR ──
  142:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'55%+ in Intermediate', entry:'Sindh University Test',
    programs:['BS Sciences','BS Arts','BS Commerce','LLB','BS Education','BS IT','Mass Communication','MPhil','PhD'],
    description:'University of Sindh Jamshoro, established in 1947, is one of Pakistan\'s oldest and largest public universities. As the premier institution of Sindh, it serves thousands of students across 83 departments and institutes.',
    highlights:['80+ Years Heritage','Public University','83 Departments','Sindh\'s Premier Uni'],
    scholarships:'Government, merit & need-based scholarships', hostel:'Separate hostels available' },
  143:{ fee:'Rs. 30–60K/sem', feeNum:45000, merit:'75%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BDS','DPT','BS Nursing','Doctor of Pharmacy','Allied Health'],
    description:'Liaquat University of Medical & Health Sciences (LUMHS) Jamshoro is Sindh\'s largest public medical university, established in 1881. It operates multiple teaching hospitals and is the primary medical institution for interior Sindh.',
    highlights:['140+ Years Heritage','Public Medical','Teaching Hospitals','Interior Sindh'],
    scholarships:'Government & merit-based scholarships', hostel:'Separate hostels available' },
  145:{ fee:'Rs. 80–150K/sem', feeNum:115000, merit:'75%+ aggregate (MDCAT)', entry:'MDCAT / Isra Test',
    programs:['MBBS','BDS','DPT','Doctor of Pharmacy','BS Allied Health'],
    description:'Isra University Hyderabad is a private medical university established in 1997. It operates a modern teaching hospital in Hyderabad and provides quality medical education to students from Sindh and Balochistan.',
    highlights:['Private Medical Uni','Teaching Hospital','Hyderabad Campus','Modern Facilities'],
    scholarships:'Merit & need-based scholarships', hostel:'Separate hostels available' },
  147:{ fee:'Rs. 20–50K/sem', feeNum:35000, merit:'65%+ in Intermediate', entry:'Sukkur IBA Test',
    programs:['BBA','MBA','BS CS','BS SE','BE Civil','BE Electrical','BS Economics','BS Education'],
    description:'Sukkur IBA University is a public university established in 1994 with a strong focus on business and technology education. Known for producing highly employable graduates, it has transformed higher education access in interior Sindh.',
    highlights:['Interior Sindh Leader','Business & Tech','Employability Focus','Public University'],
    scholarships:'Generous merit & need-based scholarships', hostel:'On-campus hostel available' },
  149:{ fee:'Rs. 20–40K/sem', feeNum:30000, merit:'60%+ in FSc Pre-Engineering', entry:'ECAT / QUEST Test',
    programs:['BE Civil Eng','BE Electrical Eng','BE Mechanical Eng','BE Computer Eng','BS CS'],
    description:'Quaid-e-Awam University of Engineering, Science & Technology (QUEST) Nawabshah is a public engineering university in Sindh, established in 1974. It is the premier engineering institution for interior Sindh students.',
    highlights:['Public Engineering','Interior Sindh','ECAT Based Admission','50+ Years Heritage'],
    scholarships:'Government & merit scholarships', hostel:'On-campus hostel available' },

  // ── KPK ──
  159:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'ICU Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS IT','BS Business','MA','MSc','MPhil'],
    description:'Islamia College University (ICU) Peshawar is one of Pakistan\'s most historic institutions, established in 1913 during the British era. It is a cherished symbol of Pashtun culture and academic heritage, offering diverse programs.',
    highlights:['110+ Years Heritage','Historic Institution','Pashtun Heritage','Public University'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  160:{ fee:'Rs. 30–60K/sem', feeNum:45000, merit:'60%+ in FSc (ETEA)', entry:'ETEA',
    programs:['BS Civil Eng','BS Electrical Eng','BS Mechanical Eng','BS Computer Eng','BS CS','BS Industrial Eng'],
    description:'University of Engineering & Technology (UET) Peshawar is KPK\'s premier public engineering university, founded in 1952. It is affiliated with ETEA and produces highly skilled engineers for Pakistan\'s construction and technology sectors.',
    highlights:['KPK\'s Top Engineering','ETEA Based','70+ Years Heritage','Public University'],
    scholarships:'Merit & HEC scholarships', hostel:'Separate hostels available' },
  161:{ fee:'Rs. 50–100K/sem', feeNum:75000, merit:'75%+ aggregate (MDCAT)', entry:'KMU / MDCAT',
    programs:['MBBS','BDS','Doctor of Pharmacy','DPT','BS Nursing','BS Allied Health'],
    description:'Khyber Medical University (KMU) Peshawar is KPK\'s premier public medical university, established in 2007. It regulates and oversees medical education across all of KPK and supervises multiple affiliated medical colleges.',
    highlights:['KPK\'s Top Medical Uni','Regulatory Body','Multiple Affiliates','Modern Facilities'],
    scholarships:'Government & merit-based scholarships', hostel:'Separate hostels available' },
  162:{ fee:'Rs. 40–70K/sem', feeNum:55000, merit:'65%+ in Intermediate', entry:'IMSciences Test',
    programs:['BBA','MBA','BS Economics','BS Media Studies','MPA','Executive MBA'],
    description:'Institute of Management Sciences (IMSciences) Peshawar is a public business school established in 1995, recognized as one of KPK\'s top institutions for business and management education with a strong alumni network.',
    highlights:['KPK\'s Top Business School','Public Sector','Strong Alumni','Career Focused'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  170:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in FSc', entry:'Gomal University Test',
    programs:['BS Agriculture','BS Pharmacy','BS Sciences','BS Arts','BS Education','BS IT','BS Business','DVM','MPhil','PhD'],
    description:'Gomal University DI Khan, established in 1974, is one of KPK\'s largest public universities serving students from DI Khan, Tank, and South KPK regions. It offers diverse programs including agriculture, pharmacy, and sciences.',
    highlights:['Public University','South KPK','Diverse Programs','50+ Years Heritage'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  172:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'50%+ in Intermediate', entry:'UOM Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS IT','BS Education','BS Business','MPhil'],
    description:'University of Malakand (UOM) Chakdara is a public university in Lower Dir, KPK, established in 2001. It provides affordable higher education to students from Malakand Division including Dir, Swat, and Chitral.',
    highlights:['Malakand Division','Public University','Affordable Fees','Mountain Region'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  175:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'50%+ in Intermediate', entry:'HU Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS IT','BS Engineering','BS Education','MPhil','PhD'],
    description:'Hazara University Mansehra is a public university established in 2002, serving the Hazara Division of KPK including Mansehra, Abbottabad, Battagram, and Kohistan. It offers affordable higher education in a scenic mountain setting.',
    highlights:['Hazara Division','Public University','Mountain Setting','Affordable Education'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  179:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'AWKUM Entry Test',
    programs:['BS Sciences','BS Arts','BS Business','BS Engineering','BS Pharmacy','BS IT','BS Education','MPhil','PhD'],
    description:'Abdul Wali Khan University Mardan (AWKUM) is a public university established in 2009, named after the legendary Pashtun leader. It serves as the primary higher education institution for Mardan and Charsadda districts of KPK.',
    highlights:['Mardan Campus','Public University','Named After AWK','Diverse Programs'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },

  // ── BALOCHISTAN ──
  198:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'50%+ in Intermediate', entry:'UOB Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','LLB','BS Engineering','BS IT','BS Social Sciences','MPhil','PhD'],
    description:'University of Balochistan (UOB) Quetta is Balochistan\'s oldest and largest public university, established in 1970. It is the premier institution for higher education in the province, serving students from all across Balochistan.',
    highlights:['Balochistan\'s Oldest Uni','Public Sector','55+ Years Heritage','Quetta Campus'],
    scholarships:'Government, provincial & merit scholarships', hostel:'Separate hostels available' },
  200:{ fee:'Rs. 20–45K/sem', feeNum:32000, merit:'55%+ in FSc', entry:'BUITEMS Entry Test',
    programs:['BS CS','BS SE','BS EE','BS Civil Eng','BBA','MBA','BS Architecture','BS Textile'],
    description:'Balochistan University of IT, Engineering & Management Sciences (BUITEMS) Quetta is Balochistan\'s leading public technology university, established in 2002. It has transformed technical education in the province with modern programs.',
    highlights:['Tech & Engineering Focus','Public University','Modern Programs','Quetta Campus'],
    scholarships:'Merit, provincial & HEC scholarships', hostel:'On-campus hostel available' },

  // ── AJK & GILGIT-BALTISTAN ──
  210:{ fee:'Rs. 20–45K/sem', feeNum:32000, merit:'60%+ in FSc', entry:'MUST Entry Test',
    programs:['BS CS','BS SE','BS EE','BS Civil Eng','BS Telecom','BBA','MBA'],
    description:'Mirpur University of Science & Technology (MUST) is AJK\'s premier public engineering university, established in 1980. It has played a central role in developing a skilled technical workforce in Azad Kashmir.',
    highlights:['AJK\'s Top Engineering','Public University','45+ Years Heritage','Technical Focus'],
    scholarships:'AJK government & merit scholarships', hostel:'On-campus hostel available' },
  211:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'50%+ in Intermediate', entry:'UAJK Entry Test',
    programs:['BS Sciences','BS Arts','BS Education','BS IT','BS Business','BS Social Sciences','MPhil','PhD'],
    description:'University of Azad Jammu & Kashmir (UAJK) Muzaffarabad is the state university of AJK, established in 1980. It is the flagship university of Azad Kashmir, offering diverse programs and serving as a center of higher education for the region.',
    highlights:['AJK\'s Flagship Uni','State University','Public Sector','Muzaffarabad Campus'],
    scholarships:'AJK government, merit & need-based scholarships', hostel:'Separate hostels available' },
  217:{ fee:'Rs. 15–35K/sem', feeNum:25000, merit:'55%+ in Intermediate', entry:'KIU Entry Test',
    programs:['BS Sciences','BS Social Sciences','BS IT','BS CS','BS Engineering','BS Education','MPhil','PhD'],
    description:'Karakoram International University (KIU) Gilgit is the only public university in Gilgit-Baltistan, established in 2002. Located amid the world\'s highest mountain ranges, it is a vital center of education and research for the GB region.',
    highlights:['GB\'s Only Public Uni','World\'s Highest Campus','Public Sector','Mountain Research'],
    scholarships:'GB government, AKES & merit scholarships', hostel:'On-campus hostel available' }
};
const LOGO_OVERRIDES = {
  'nust.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/a/aa/NUSTuniversitylogo.jpg',
  'lums.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/thumb/3/38/Lahore_University_of_Management_Sciences_Logo.svg/500px-Lahore_University_of_Management_Sciences_Logo.svg.png',
  'uet.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/University_of_Engineering_and_Technology_Lahore_logo.svg/500px-University_of_Engineering_and_Technology_Lahore_logo.svg.png',
  'iba.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/1/1e/Institute_of_Business_Administration%2C_Karachi_%28logo%29.png',
  'comsats.edu.pk':    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/COMSATS_new_logo.jpg/250px-COMSATS_new_logo.jpg',
  'nu.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/National_University_of_Computer_and_Emerging_Sciences_logo.png/250px-National_University_of_Computer_and_Emerging_Sciences_logo.png',
  'qau.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/3/35/Quaid-i-Azam_University_logo.png',
  'giki.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/5/59/GIKI_logo_with_text.png',
  'pieas.edu.pk':      'https://upload.wikimedia.org/wikipedia/en/e/e0/PIEAS_Logo.jpg',
  'neduet.edu.pk':     'https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/NEDUET_logo.svg/500px-NEDUET_logo.svg.png',
  'pu.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/c/c8/University_of_the_Punjab_logo.png',
  'aku.edu':           'https://upload.wikimedia.org/wikipedia/en/6/64/Aga_Khan_University_Logo.png',
  'habib.edu.pk':      'https://upload.wikimedia.org/wikipedia/en/3/38/Habib_University.jpg',
  'au.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/6/61/Air_University_Pakistan_Insignia.png',
  'itu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/d/d9/Information_Technology_University.png',
  'muet.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Mehran_University_of_Engineering_and_Technology_logo.svg/500px-Mehran_University_of_Engineering_and_Technology_logo.svg.png',
  'ucp.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/e/eb/University_of_Central_Punjab_%28logo%29.jpg',
  'szabist.edu.pk':    'https://upload.wikimedia.org/wikipedia/en/f/f9/SZABIST-University-Logo-Blue-Horizontal.png',
  'gcu.edu.pk':        'https://upload.wikimedia.org/wikipedia/commons/f/f5/Government_College_University%2CLogo.png',
  'ist.edu.pk':        'https://upload.wikimedia.org/wikipedia/commons/2/23/Logo_IST.png',
  'fccollege.edu.pk':  'https://upload.wikimedia.org/wikipedia/en/9/97/Forman_Christian_College_logo.png',
  'numl.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/d/d5/National_University_of_Modern_Languages_%28logo%29.jpg',
  'uettaxila.edu.pk':  'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/UET_Taxila_logo.svg/500px-UET_Taxila_logo.svg.png',
  'duhs.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/b/bf/Logo_of_Dow_University_of_Health_Sciences.gif',
  'uhs.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/University_of_Health_Sciences_Lahore_Logo.svg/500px-University_of_Health_Sciences_Lahore_Logo.svg.png',
  'bzu.edu.pk':        'https://upload.wikimedia.org/wikipedia/commons/9/9c/BZU-Multan.png',
  'iiu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/1/1e/International_Islamic_University%2C_Islamabad_%28crest%29.png',
  'uop.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/d/de/University_of_Peshawar_logo.png',
  'nca.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/f/f5/National_College_of_Arts_%28emblem%29.jpg',
  'bahria.edu.pk':     'https://bahria.edu.pk/Content/images/bu_logo.png',
  // 188 basic universities — Wikipedia verified logos
  'aiou.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/8/87/Allama_Iqbal_Open_University_logo.png',
  'vu.edu.pk':         'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/VU_Logo.png/250px-VU_Logo.png',
  'lcwu.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/e/e0/LCWU_Lahore_logo.PNG',
  'kemu.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/4/4f/King_Edward_Medical_University.png',
  'uvas.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/0/0b/UVAS_Lahore.jpg',
  'uaf.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/2/2e/Agriculture_University_Faisalabad_emblem.png',
  'ntu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/e/e4/National_Textile_University_Logo.png',
  'gcuf.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/0/01/Government_College_University_Logo.jpg',
  'uos.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/c/c3/University_of_Sargodha.png',
  'uog.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/c/c4/University_of_Gujrat_Logo.png',
  'uok.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/d/d9/Karachi_University_logo.png',
  'usindh.edu.pk':     'https://upload.wikimedia.org/wikipedia/en/7/7c/University_of_Sindh_%28logo%29.png',
  'lumhs.edu.pk':      'https://upload.wikimedia.org/wikipedia/en/7/7c/Liaquat_University_of_Medical_and_Health_Sciences_%28crest%29.jpg',
  'iba-suk.edu.pk':    'https://upload.wikimedia.org/wikipedia/commons/d/d3/SIBA_Logo.jpg',
  'quest.edu.pk':      'https://upload.wikimedia.org/wikipedia/commons/b/b9/Logo_of_Quaid-e-Awam_university_of_engineering_science_and_technology.jpg',
  'uetpeshawar.edu.pk':'https://upload.wikimedia.org/wikipedia/en/thumb/9/95/University_of_Engineering_and_Technology_Peshawar_logo.svg/250px-University_of_Engineering_and_Technology_Peshawar_logo.svg.png',
  'kmu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/f/f1/KMU_Peshawar.jpg',
  'gu.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/5/57/Gomal_University_logo.png',
  'uom.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/a/a3/University_of_Malakand_%28crest%29.jpg',
  'hu.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/2/28/Hazara_University_logo.jpeg',
  'kust.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/0/06/KUST.png',
  'uob.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/3/30/University_of_Balochistan_logo.jpg',
  'buitms.edu.pk':     'https://upload.wikimedia.org/wikipedia/en/f/fd/BUITEMS_logo.png',
  'must.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/2/2c/Mirpur_University_Of_Science_And_Technology_Logo.png',
  'ajku.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/4/49/University_Of_Azad_Jammu_And_Kashmir_Logo.png',
  'kiu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/a/a8/Karakoram_International_University_%28logo%29.jpg',
};
const MERIT_MAP = {
  1:85,2:84,3:75,4:82,5:75,6:65,7:60,8:82,9:87,10:72,
  11:55,12:87,13:75,14:65,15:60,16:72,17:60,18:60,19:65,20:65,
  21:65,22:70,23:55,24:72,25:78,26:78,27:55,28:55,29:55,30:60,
  31:62,32:45,33:45,34:65,35:60,36:55,37:62,38:65,39:60,40:82,
  41:62,42:55,43:65,44:55,45:55,
  46:55,47:82,48:84,49:60,50:60,51:62,52:57,53:62,54:55,55:57,
  56:55,57:55,58:60,59:63,60:57,61:55,62:60,63:55,64:62,65:55,
  66:55,67:55,68:55,
  69:55,70:55,71:77,72:82,73:55,74:62,
  75:57,76:55,77:62,78:77,79:55,80:55,
  81:55,82:55,83:55,84:55,85:57,86:77,87:62,88:55,89:60,90:55,
  91:55,92:55,93:62,94:55,95:57,96:55,97:67,98:50,99:50,100:50,
  101:50,102:50,103:62,104:50,105:50,106:50,107:50,108:50,109:50,
  110:50,111:62,112:57,113:55,
  114:55,115:62,116:62,117:65,118:80,119:65,120:60,121:80,122:67,
  123:60,124:62,125:55,126:60,127:60,128:55,129:55,130:55,131:57,
  132:55,133:67,134:57,135:55,136:60,137:55,138:67,139:60,140:55,141:55,
  142:50,143:75,144:50,145:72,146:55,147:62,148:50,149:62,150:50,
  151:72,152:50,153:72,154:50,155:50,156:55,157:50,158:55,
  159:55,160:65,161:75,162:65,163:55,164:62,165:65,166:57,167:57,
  168:57,169:55,170:55,171:57,172:50,173:50,174:50,175:50,176:55,
  177:57,178:50,179:55,180:50,181:57,182:50,183:50,184:50,185:50,
  186:50,187:50,188:50,189:55,190:50,191:50,192:50,193:50,194:57,
  195:57,196:55,197:50,
  198:50,199:72,200:55,201:50,202:50,203:50,204:50,205:57,206:50,
  207:50,208:50,209:57,
  210:62,211:50,212:50,213:55,214:50,215:50,216:50,
  217:57,218:50
};
const VERIFIED_MERIT = {
  // Add verified entries here — empty until first verified submission
};
const CITY_COORDS = {
  'Islamabad':[33.6844,73.0479],'Rawalpindi':[33.5651,73.0169],'Wah':[33.7830,72.7286],'Attock':[33.7660,72.3600],
  'Lahore':[31.5204,74.3587],'Faisalabad':[31.4504,73.1350],'Multan':[30.1575,71.5249],
  'Gujranwala':[32.1877,74.1945],'Sialkot':[32.4945,74.5229],'Sargodha':[32.0836,72.6711],
  'Gujrat':[32.5739,74.0786],'Bahawalpur':[29.3956,71.6836],'Sheikhupura':[31.7167,73.9850],
  'Okara':[30.8138,73.4536],'Mianwali':[32.5847,71.5433],'Jhang':[31.2781,72.3220],
  'Sahiwal':[30.6706,73.1077],'Jhelum':[32.9343,73.7214],'Chakwal':[32.9332,72.8505],
  'Narowal':[32.0991,74.8761],'Hafizabad':[32.0709,73.6881],'DG Khan':[30.0489,70.6330],
  'Dera Ghazi Khan':[30.0489,70.6330],'Layyah':[30.9591,70.9396],'Khanewal':[30.3006,71.9327],
  'Nankana Sahib':[31.4505,73.7067],'Kasur':[31.1166,74.4501],'Bhakkar':[31.6271,71.0645],
  'Vehari':[30.0451,72.3491],'Toba Tek Singh':[30.9774,72.4827],
  'Karachi':[24.8607,67.0011],'Hyderabad':[25.3960,68.3578],'Sukkur':[27.6995,68.8673],
  'Jamshoro':[25.4211,68.2828],'Larkana':[27.5570,68.2142],'Nawabshah':[26.2442,68.4102],
  'Khairpur':[27.5295,68.7586],'Tandojam':[25.4280,68.5336],'Mirpurkhas':[25.5276,69.0084],
  'Peshawar':[34.0151,71.5249],'Abbottabad':[34.1463,73.2117],'Mardan':[34.1985,72.0440],
  'Mansehra':[34.3293,73.2063],'Nowshera':[34.0153,71.9747],'Swat':[35.2227,72.4258],
  'DI Khan':[31.8313,70.9017],'Dera Ismail Khan':[31.8313,70.9017],'Kohat':[33.5869,71.4414],
  'Bannu':[32.9887,70.6045],'Chitral':[35.8518,71.7865],'Swabi':[34.1203,72.4699],
  'Haripur':[33.9950,72.9407],'Buner':[34.5082,72.4947],'Shangla':[35.0200,72.5300],
  'Dir':[35.2018,71.8766],'Karak':[33.1172,71.0936],'Batagram':[34.6770,73.0269],
  'Quetta':[30.1798,66.9750],'Turbat':[26.0022,63.0442],'Khuzdar':[27.8000,66.6167],
  'Hub':[25.0325,66.8960],'Sibi':[29.5430,67.8770],'Loralai':[30.3700,68.5942],
  'Muzaffarabad':[34.3703,73.4705],'Mirpur':[33.1532,73.7508],'Rawalakot':[33.8591,73.7602],
  'Bagh':[33.9866,73.7832],'Kotli':[33.5170,73.9022],
  'Gilgit':[35.9221,74.3083],'Skardu':[35.2971,75.6341],
  'Online':[33.6844,73.0479],
};
const MERIT_TRENDS = {
  1:{y:['2022','2023','2024'],m:[83,84,85]}, 2:{y:['2022','2023','2024'],m:[81,82,84]},
  3:{y:['2022','2023','2024'],m:[73,74,75]}, 4:{y:['2022','2023','2024'],m:[81,83,82]},
  5:{y:['2022','2023','2024'],m:[73,74,75]}, 6:{y:['2022','2023','2024'],m:[63,64,65]},
  7:{y:['2022','2023','2024'],m:[58,59,60]}, 8:{y:['2022','2023','2024'],m:[80,81,82]},
  9:{y:['2022','2023','2024'],m:[86,86,87]},10:{y:['2022','2023','2024'],m:[70,71,72]},
  12:{y:['2022','2023','2024'],m:[85,86,87]},13:{y:['2022','2023','2024'],m:[73,74,75]},
  14:{y:['2022','2023','2024'],m:[63,64,65]},16:{y:['2022','2023','2024'],m:[70,71,72]},
  22:{y:['2022','2023','2024'],m:[68,69,70]},24:{y:['2022','2023','2024'],m:[70,71,72]},
  32:{y:['2022','2023','2024'],m:[43,44,45]},33:{y:['2022','2023','2024'],m:[43,44,45]},
  47:{y:['2022','2023','2024'],m:[80,81,82]},48:{y:['2022','2023','2024'],m:[82,83,84]},
  51:{y:['2022','2023','2024'],m:[60,61,62]},71:{y:['2022','2023','2024'],m:[75,76,77]},
  72:{y:['2022','2023','2024'],m:[80,81,82]},97:{y:['2022','2023','2024'],m:[65,66,67]},
  115:{y:['2022','2023','2024'],m:[60,61,62]},118:{y:['2022','2023','2024'],m:[78,79,80]},
  160:{y:['2022','2023','2024'],m:[63,64,65]},200:{y:['2022','2023','2024'],m:[53,54,55]},
};
