// ─────────────────────────────────────────────────
// TaleemPK university seed data (extracted from index.html
// for faster first paint). Loaded synchronously before the
// main inline script — do not add defer/async to its tag.
// ─────────────────────────────────────────────────
const UNIVERSITIES = [
  {
    id:1, rank:1, name:"NUST", full:"National University of Sciences & Technology",
    city:"Islamabad", type:"public", icon:"🏛️",
    tags:["public","engineering","business"],
    fee:"Rs. 1.2–1.4L/sem", feeNum:130000,
    merit:"140+/200 NET",
    entry:"NUST NET",
    programs:["Engineering","CS","Business","Biosciences","Architecture","Social Sciences"],
    seats:"~4,000/year",
    established:1991,
    website:"nust.edu.pk",
    description:"Pakistan's most prestigious engineering university, under the Defence Ministry. Located at Islamabad H-12.",
    highlights:["QS World Ranked","Multiple campuses","Strong industry links","Best research output"],
    scholarships:"Merit + Need-based available",
    hostel:"Available on campus"
  },
  {
    id:2, rank:2, name:"LUMS", full:"Lahore University of Management Sciences",
    city:"Lahore", type:"private", icon:"🎓",
    tags:["private","business","engineering"],
    fee:"Rs. 6.9–8.2L/sem", feeNum:755000,
    feeYear:"2026-27",
    feeDetails:[
      {label:"Undergraduate tuition", value:"Rs. 45,800 / credit hour"},
      {label:"Undergraduate (per semester, ~15–18 CH)", value:"~Rs. 6.9–8.2 lakh"},
      {label:"MBA — full-time (approx)", value:"~Rs. 1.4–1.8M / semester"},
      {label:"Executive MBA (approx)", value:"~Rs. 2M / semester"},
      {label:"LGAT test registration", value:"Rs. 3,000"},
    ],
    feeNote:"Undergraduate fee is official (per-credit-hour model, FY 2026-27). Graduate (MBA/EMBA) figures are approximate — confirm exact fees at lums.edu.pk. LUMS offers need-blind financial aid; around 40% of students do not pay the full fee.",
    merit:"70%+ Matric+FSc, SAT/LCAT",
    entry:"LCAT / SAT",
    programs:["MBA","Executive MBA (EMBA)","BBA","CS","Economics","Law","Social Sciences","Engineering","Physics"],
    seats:"~1,200/year",
    established:1984,
    website:"lums.edu.pk",
    description:"Pakistan's #1 business and management university with world-class faculty and top corporate placements.",
    highlights:["FT Global MBA ranked","Need-blind scholarships","Strong alumni network","International collaborations"],
    scholarships:"Need-blind financial aid — 40% students pay no full fee",
    hostel:"Available"
  },
  {
    id:3, rank:3, name:"UET Lahore", full:"University of Engineering & Technology Lahore",
    city:"Lahore", type:"public", icon:"⚙️",
    tags:["public","engineering"],
    fee:"Rs. 60–80K/sem", feeNum:70000,
    merit:"ECAT required, 60%+ FSc",
    entry:"ECAT",
    programs:["Civil Engg","Electrical Engg","Mechanical Engg","CS","Chemical Engg","Arch"],
    seats:"~3,500/year",
    established:1921,
    website:"uet.edu.pk",
    description:"Pakistan's oldest engineering university with over 100 years of heritage. Main campus in Lahore.",
    highlights:["Oldest eng university","Government subsidized fees","PEC accredited","Multiple sub-campuses"],
    scholarships:"Need-based + HEC scholarships",
    hostel:"Available"
  },
  {
    id:4, rank:4, name:"IBA Karachi", full:"Institute of Business Administration Karachi",
    city:"Karachi", type:"public", icon:"💼",
    tags:["public","business"],
    fee:"Rs. 4.4–5L/sem", feeNum:470000,
    feeYear:"2025-26 official",
    feeDetails:[
      {label:"Undergraduate (BBA / BS)", value:"Rs. 29,400 / credit hour"},
      {label:"MBA", value:"Rs. 36,750 / credit hour"},
      {label:"Executive MBA (EMBA)", value:"Rs. 4,000,000 total"},
      {label:"MS Programs", value:"Rs. 24,800–32,550 / credit hour"},
      {label:"Hostel (per semester)", value:"Rs. 114,840–133,584"},
      {label:"Transport (annual)", value:"Rs. 45,000–65,000"},
      {label:"One-time Admission Charges", value:"Rs. 115,000"},
      {label:"Student Activity Charges", value:"Rs. 7,000"},
    ],
    feeNote:"Fees are charged per credit hour, so the per-semester total depends on your course load. Always confirm the latest figures on iba.edu.pk.",
    merit:"85%+ marks, IBA test",
    entry:"IBA Aptitude Test",
    programs:["BBA","MBA","Executive MBA (EMBA)","MS Computer Science","BS CS","BS Economics","BS Accounting","BS Social Sciences"],
    seats:"~800/year",
    established:1955,
    website:"iba.edu.pk",
    description:"Pakistan and South Asia's oldest business school, under the Sindh Government. A top corporate recruitment destination.",
    highlights:["Oldest biz school in Asia","Strong corporate ties","Generous need-based aid","Harvard-affiliated curriculum"],
    scholarships:"Merit + Need-based",
    hostel:"Available"
  },
  {
    id:5, rank:5, name:"FAST NUCES", full:"FAST National University of Computer & Emerging Sciences",
    city:"Karachi / Lahore / Islamabad / Peshawar", type:"private", icon:"💻",
    tags:["private","engineering"],
    fee:"Rs. 1.8–2.2L/sem", feeNum:200000,
    feeYear:"2026-27",
    feeDetails:[
      {label:"Tuition (BS / MS / PhD)", value:"Rs. 12,000 / credit hour"},
      {label:"Per semester (~15–18 CH)", value:"~Rs. 1.8–2.2 lakh"},
      {label:"One-time Admission Fee", value:"Rs. 30,000"},
      {label:"Security Deposit (refundable)", value:"Rs. 20,000"},
      {label:"Student Activity (per semester)", value:"Rs. 2,500"},
    ],
    feeNote:"The same per-credit-hour rate applies to BS, MS and PhD programs across all campuses. Per-semester total depends on your course load. Confirm at nu.edu.pk.",
    merit:"65%+ FSc, NAT/FAST test",
    entry:"NUCES Aptitude Test / NAT",
    programs:["BSCS","BSSE","BSAI","Electrical Engg","Data Science","Business"],
    seats:"~5,000/year (all campuses)",
    established:2000,
    website:"nu.edu.pk",
    description:"Pakistan's best CS and Software Engineering university with campuses in 5 major cities. Industry-focused curriculum.",
    highlights:["Top CS university","5 campuses nationwide","Strong tech industry links","Google/Microsoft alumni"],
    scholarships:"Merit-based waivers",
    hostel:"Available at most campuses"
  },
  {
    id:6, rank:6, name:"COMSATS", full:"COMSATS University Islamabad",
    city:"Islamabad / Lahore / Karachi / +5 cities", type:"public", icon:"🔬",
    tags:["public","engineering","business"],
    fee:"Rs. 1.3–1.5L/sem", feeNum:138000,
    merit:"60%+ FSc, COMSATS test",
    entry:"CIS-IET",
    programs:["BSCS","BS EE","BBA","Pharmacy","Biosciences","Math"],
    seats:"~8,000/year",
    established:1998,
    website:"comsats.edu.pk",
    description:"A federal university with 8 campuses nationwide, offering affordable quality education with a strong research focus.",
    highlights:["8 campuses nationwide","HEC O-category","Affordable fees","Strong research"],
    scholarships:"HEC + COMSATS scholarships",
    hostel:"Available"
  },
  {
    id:7, rank:7, name:"QAU", full:"Quaid-i-Azam University",
    city:"Islamabad", type:"public", icon:"🏫",
    tags:["public"],
    fee:"Rs. 15–25K/sem", feeNum:20000,
    merit:"Merit-based, 60%+ FSc",
    entry:"No entry test (merit-based)",
    programs:["Physics","Chemistry","Biology","Biochem","International Relations","Law"],
    seats:"~3,000/year",
    established:1967,
    website:"qau.edu.pk",
    description:"HEC's #1 ranked general category university. Pakistan's best in sciences and social sciences. Very affordable fees.",
    highlights:["HEC #1 ranked","Cheapest quality education","Strong research","Beautiful campus"],
    scholarships:"Extensive need-based aid",
    hostel:"Available"
  },
  {
    id:8, rank:8, name:"GIKI", full:"Ghulam Ishaq Khan Institute",
    city:"Swabi, KPK", type:"private", icon:"⚙️",
    tags:["private","engineering"],
    fee:"Rs. 2–2.5L/sem", feeNum:220000,
    merit:"70%+ FSc, GIKI test",
    entry:"GIKI Entry Test",
    programs:["Mechanical Engg","Electrical Engg","CS","Chemical Engg","Materials Science"],
    seats:"~600/year",
    established:1993,
    website:"giki.edu.pk",
    description:"A fully residential, industry-funded engineering university of the highest quality. GIKI graduates rank among Pakistan's top earners.",
    highlights:["Fully residential","Industry-funded","Top engineering output","Beautiful Swabi campus"],
    scholarships:"Merit scholarships available",
    hostel:"Mandatory residential"
  },
  {
    id:9, rank:9, name:"PIEAS", full:"Pakistan Institute of Engineering & Applied Sciences",
    city:"Islamabad", type:"public", icon:"⚛️",
    tags:["public","engineering"],
    fee:"Almost FREE", feeNum:5000,
    merit:"Very high — PIEAS test",
    entry:"PIEAS Entry Test",
    programs:["Nuclear Engineering","Electrical Engg","CS","Physics","Mechanical Engg"],
    seats:"~200/year",
    established:1967,
    website:"pieas.edu.pk",
    description:"A fully-funded university under PAEC offering almost free education. Pakistan's most selective university.",
    highlights:["Almost free tuition","Stipend provided","Most selective","Nuclear engineering #1"],
    scholarships:"Full scholarship for all students",
    hostel:"Free residential"
  },
  {
    id:10, rank:10, name:"NED University", full:"NED University of Engineering & Technology",
    city:"Karachi", type:"public", icon:"🏗️",
    tags:["public","engineering"],
    fee:"Rs. 20–35K/sem", feeNum:28000,
    merit:"60%+ FSc, ECAT or UET test",
    entry:"NTS / ECAT",
    programs:["Civil Engg","Electrical","Mechanical","CS","Architecture","Industrial Engg"],
    seats:"~3,000/year",
    established:1921,
    website:"neduet.edu.pk",
    description:"Karachi's first engineering university, under the Sindh Government. Offers affordable, quality engineering education.",
    highlights:["100+ year history","Affordable fees","Strong Karachi industry links","PEC accredited"],
    scholarships:"Sindh govt + need-based",
    hostel:"Available"
  },
  {
    id:11, rank:11, name:"University of Punjab", full:"University of the Punjab",
    city:"Lahore", type:"public", icon:"🏛️",
    tags:["public"],
    fee:"Rs. 18–30K/sem", feeNum:24000,
    merit:"Merit-based by program",
    entry:"Various by program",
    programs:["CS","Commerce","Law","Medicine","Engineering","Social Sciences","Arts"],
    seats:"~15,000/year",
    established:1882,
    website:"pu.edu.pk",
    description:"Pakistan's oldest university (est. 1882) with the largest enrollment. Diverse programs and affordable public fees.",
    highlights:["Oldest in Pakistan","Largest university","Diverse programs","Extremely affordable"],
    scholarships:"Extensive",
    hostel:"Available"
  },
  {
    id:12, rank:12, name:"Aga Khan University", full:"Aga Khan University",
    city:"Karachi", type:"private", icon:"🏥",
    tags:["private","medical"],
    fee:"Rs. 4–6L/sem", feeNum:500000,
    merit:"Very high — 85%+ overall",
    entry:"AKU Admission Test (AAT)",
    programs:["MBBS","BScN","Nursing","Education","Medicine","Public Health"],
    seats:"~200/year",
    established:1983,
    website:"aku.edu",
    description:"Pakistan's best medical university with a world-class attached hospital. The AKU degree is internationally recognized.",
    highlights:["World-class medical school","International accreditation","AKU Hospital","Global alumni"],
    scholarships:"Need-based — generous",
    hostel:"Available"
  },
  {
    id:13, rank:13, name:"Habib University", full:"Habib University",
    city:"Karachi", type:"private", icon:"🎨",
    tags:["private","engineering","arts"],
    fee:"Rs. 2.5–3L/sem", feeNum:275000,
    merit:"70%+ marks, HU test",
    entry:"Habib University Test",
    programs:["Computer Science","Electrical Engg","Social Dev & Policy","Philosophy","Dhanani School"],
    seats:"~400/year",
    established:2014,
    website:"habib.edu.pk",
    description:"Pakistan's newest liberal arts and engineering university with a unique interdisciplinary model. Beautiful campus in Karachi.",
    highlights:["Liberal arts + engineering","Need-blind admissions","Unique curriculum","Award-winning campus"],
    scholarships:"Strong need-blind program — 30%+ on aid",
    hostel:"Available"
  },
  {
    id:14, rank:14, name:"Air University", full:"Air University Islamabad",
    city:"Islamabad", type:"public", icon:"✈️",
    tags:["public","engineering"],
    fee:"Rs. 60–80K/sem", feeNum:70000,
    merit:"60%+ FSc, entry test",
    entry:"AU Admission Test",
    programs:["Aerospace Engg","Avionics","CS","Electrical Engg","Management","Humanities"],
    seats:"~1,500/year",
    established:2002,
    website:"au.edu.pk",
    description:"A university under the Pakistan Air Force — the country's only aerospace engineering institution. Located in Islamabad.",
    highlights:["Only aerospace engg in PK","PAF-affiliated","Modern campus","Strong aviation industry links"],
    scholarships:"PAF + merit scholarships",
    hostel:"Available"
  },
  {
    id:15, rank:15, name:"Bahria University", full:"Bahria University",
    city:"Islamabad / Karachi / Lahore", type:"public", icon:"⚓",
    tags:["public","engineering","business"],
    fee:"Rs. 70–90K/sem", feeNum:80000,
    merit:"60%+ FSc, BU test",
    entry:"Bahria Admission Test",
    programs:["CS","Electrical Engg","Management Sciences","Earth Sciences","Psychology","Law"],
    seats:"~4,000/year",
    established:2000,
    website:"bahria.edu.pk",
    description:"A university under the Pakistan Navy with 3 campuses. Discipline-oriented environment with strong management programs.",
    highlights:["Navy-affiliated","3 campuses","Strong management","Disciplined environment"],
    scholarships:"Navy + merit-based",
    hostel:"Available"
  },
  {
    id:16, rank:16, name:"ITU", full:"Information Technology University Punjab",
    city:"Lahore", type:"public", icon:"💡",
    tags:["public","engineering"],
    fee:"Rs. 30–50K/sem", feeNum:40000,
    merit:"65%+ marks, ITU test",
    entry:"ITU Admission Test",
    programs:["CS","Data Science","AI","Electrical Engg","Design & Innovation"],
    seats:"~800/year",
    established:2012,
    website:"itu.edu.pk",
    description:"Punjab Government's newest tech university focused on innovation and entrepreneurship. Vibrant startup culture.",
    highlights:["Innovation-focused","Punjab govt","Startup ecosystem","Modern curriculum"],
    scholarships:"Punjab govt scholarships",
    hostel:"Available"
  },
  {
    id:17, rank:17, name:"MUET", full:"Mehran University of Engineering & Technology",
    city:"Jamshoro, Sindh", type:"public", icon:"🏗️",
    tags:["public","engineering"],
    fee:"Rs. 15–25K/sem", feeNum:20000,
    merit:"60%+ FSc, MUET test",
    entry:"MUET Admission Test",
    programs:["Civil Engg","Electrical","Mechanical","Electronic","CS","Biomedical Engg"],
    seats:"~2,500/year",
    established:1977,
    website:"muet.edu.pk",
    description:"Sindh's top engineering university. Very affordable with strong ties to Hyderabad and Sindh's industrial sector.",
    highlights:["Top Sindh university","Very affordable","PEC accredited","Large enrollment"],
    scholarships:"Sindh govt scholarships",
    hostel:"Available"
  },
  {
    id:18, rank:18, name:"UCP", full:"University of Central Punjab",
    city:"Lahore", type:"private", icon:"🎓",
    tags:["private","business","engineering"],
    fee:"Rs. 80K–1.2L/sem", feeNum:100000,
    merit:"55%+ marks, UCP test",
    entry:"UCP Admission Test",
    programs:["BBA","MBA","CS","Law","Architecture","Pharmacy","Engineering"],
    seats:"~5,000/year",
    established:2002,
    website:"ucp.edu.pk",
    description:"Lahore's largest private university offering diverse programs with a modern campus and industry-linked education.",
    highlights:["Diverse programs","Large campus","Industry linkages","Lahore location"],
    scholarships:"Merit-based",
    hostel:"Available"
  },
  {
    id:19, rank:19, name:"SZABIST", full:"Shaheed Zulfikar Ali Bhutto Institute of Science & Technology",
    city:"Karachi / Islamabad / Larkana", type:"private", icon:"📊",
    tags:["private","business","engineering"],
    fee:"Rs. 1–1.5L/sem", feeNum:120000,
    merit:"60%+ marks, SZABIST test",
    entry:"SZABIST Admission Test",
    programs:["MBA","BBA","CS","Media Sciences","Social Sciences","Engineering"],
    seats:"~3,000/year",
    established:1995,
    website:"szabist.edu.pk",
    description:"A university founded by PPP with campuses in Karachi, Islamabad, and Larkana. Strong in Business and Media programs.",
    highlights:["3 city campuses","Strong media programs","PPP-backed","Known alumni network"],
    scholarships:"Merit + need-based",
    hostel:"Available"
  },
  {
    id:20, rank:20, name:"GCU Lahore", full:"Government College University Lahore",
    city:"Lahore", type:"public", icon:"🏛️",
    tags:["public"],
    fee:"Rs. 5–15K/sem", feeNum:10000,
    merit:"Merit-based, 60%+",
    entry:"GCU Admission Test",
    programs:["Physics","Chemistry","Math","Economics","History","Urdu","English","Persian"],
    seats:"~5,000/year",
    established:1864,
    website:"gcu.edu.pk",
    description:"Pakistan's second oldest institution (est. 1864) with a historic campus. Pakistan's literary and intellectual elite have studied here.",
    highlights:["1864 — oldest college","Historic campus","Very affordable","Literary heritage"],
    scholarships:"Punjab govt scholarships",
    hostel:"Available"
  },
  {
    id:21, rank:21, name:"IST", full:"Institute of Space Technology",
    city:"Islamabad", type:"public", icon:"🚀",
    tags:["public","engineering"],
    fee:"Rs. 40–70K/sem", feeNum:55000,
    merit:"65%+ FSc, IST test",
    entry:"IST Admission Test",
    programs:["Aerospace Engg","Remote Sensing","Satellite Comm","CS","Electrical Engg","Math"],
    seats:"~400/year",
    established:2002,
    website:"ist.edu.pk",
    description:"A government-funded university under SUPARCO offering unique space technology programs — the only one of its kind in Pakistan.",
    highlights:["Space tech focus","SUPARCO-affiliated","Unique programs","Government funded"],
    scholarships:"SUPARCO + merit",
    hostel:"Available"
  },
  {
    id:22, rank:22, name:"Forman Christian College", full:"Forman Christian College University",
    city:"Lahore", type:"private", icon:"⛪",
    tags:["private","arts"],
    fee:"Rs. 40–80K/sem", feeNum:60000,
    merit:"60%+ marks, FCCU test",
    entry:"FCCU Admission Test",
    programs:["CS","Biology","Physics","Chemistry","Math","Social Sciences","English","Business"],
    seats:"~2,000/year",
    established:1864,
    website:"fccollege.edu.pk",
    description:"Founded in 1864, this historic Christian mission college in Lahore is known for its liberal arts tradition and beautiful campus.",
    highlights:["Historic campus","Liberal arts","American-influenced","Beautiful gardens"],
    scholarships:"Need-based available",
    hostel:"Available"
  },
  {
    id:23, rank:23, name:"NUML", full:"National University of Modern Languages",
    city:"Islamabad / Lahore / Karachi + others", type:"public", icon:"🗣️",
    tags:["public"],
    fee:"Rs. 20–40K/sem", feeNum:30000,
    merit:"50%+ marks",
    entry:"NUML Test (some programs)",
    programs:["Languages","Translation","Linguistics","Business","IT","Education","Management"],
    seats:"~4,000/year",
    established:1969,
    website:"numl.edu.pk",
    description:"Under the Ministry of Defence, NUML specializes in languages — offering 40+ language programs across multiple campuses.",
    highlights:["40+ languages","Defence-affiliated","Multiple campuses","Affordable"],
    scholarships:"Merit-based",
    hostel:"Available"
  },
  {
    id:24, rank:24, name:"UET Taxila", full:"University of Engineering & Technology Taxila",
    city:"Taxila", type:"public", icon:"⚙️",
    tags:["public","engineering"],
    fee:"Rs. 30–50K/sem", feeNum:40000,
    merit:"60%+ FSc, ECAT",
    entry:"ECAT",
    programs:["Mechanical Engg","Electrical Engg","CS","Civil Engg","Industrial Engg","Mechatronics"],
    seats:"~1,500/year",
    established:1975,
    website:"uettaxila.edu.pk",
    description:"UET's Taxila campus offering affordable engineering education near Islamabad, situated in Pakistan's industrial belt.",
    highlights:["Near Islamabad","Affordable engineering","PEC accredited","Industrial location"],
    scholarships:"HEC + merit",
    hostel:"Available"
  },
  {
    id:25, rank:25, name:"Dow University", full:"Dow University of Health Sciences",
    city:"Karachi", type:"public", icon:"🏥",
    tags:["public","medical"],
    fee:"Rs. 40–80K/sem", feeNum:60000,
    merit:"MDCAT required, 70%+",
    entry:"MDCAT",
    programs:["MBBS","BDS","Pharmacy","Nursing","Allied Health","Physical Therapy"],
    seats:"~1,200/year",
    established:2004,
    website:"duhs.edu.pk",
    description:"Karachi's largest medical university, affiliated with Dow Medical College (est. 1945) and backed by the Sindh Government.",
    highlights:["Dow Medical College legacy","Largest med uni Karachi","Affordable","Sindh govt"],
    scholarships:"Sindh govt + merit",
    hostel:"Available"
  },
  {
    id:26, rank:26, name:"UHS", full:"University of Health Sciences",
    city:"Lahore", type:"public", icon:"⚕️",
    tags:["public","medical"],
    fee:"Rs. 30–60K/sem", feeNum:45000,
    merit:"MDCAT required, 70%+",
    entry:"MDCAT",
    programs:["MBBS","BDS","Pharmacy","Nursing","Public Health","DPT"],
    seats:"~2,000+/year",
    established:2002,
    website:"uhs.edu.pk",
    description:"The regulatory body for Punjab's medical universities, with its own teaching hospitals in Lahore.",
    highlights:["Punjab regulator","Teaching hospitals","MDCAT merit","Punjab govt"],
    scholarships:"Punjab govt",
    hostel:"Available"
  },
  {
    id:27, rank:27, name:"BZU", full:"Bahauddin Zakariya University",
    city:"Multan", type:"public", icon:"🏫",
    tags:["public"],
    fee:"Rs. 15–28K/sem", feeNum:22000,
    merit:"Merit-based, 55%+",
    entry:"Program specific tests",
    programs:["CS","Engineering","Commerce","Law","Sciences","Social Sciences","Islamic Studies"],
    seats:"~6,000/year",
    established:1975,
    website:"bzu.edu.pk",
    description:"South Punjab's top university, located in Multan. Very affordable public education with a large and diverse enrollment.",
    highlights:["South Punjab #1","Very affordable","Large programs","Government-backed"],
    scholarships:"HEC + university",
    hostel:"Available"
  },
  {
    id:28, rank:28, name:"IIUI", full:"International Islamic University Islamabad",
    city:"Islamabad", type:"public", icon:"☪️",
    tags:["public"],
    fee:"Rs. 10–30K/sem", feeNum:20000,
    merit:"50%+ marks, some tests",
    entry:"IIU Test (Islamic programs)",
    programs:["Islamic Studies","Law","Engineering","CS","Languages","Business","Social Sciences"],
    seats:"~5,000/year",
    established:1980,
    website:"iiu.edu.pk",
    description:"An OIC-affiliated international university combining Islamic education with modern sciences. Welcomes international students.",
    highlights:["OIC-affiliated","International students","Islamic + modern","Very affordable"],
    scholarships:"OIC + govt scholarships",
    hostel:"Available — for international too"
  },
  {
    id:29, rank:29, name:"UoP", full:"University of Peshawar",
    city:"Peshawar", type:"public", icon:"🏔️",
    tags:["public"],
    fee:"Rs. 15–30K/sem", feeNum:22000,
    merit:"Merit-based, 55%+",
    entry:"Program specific",
    programs:["International Relations","Political Science","Pharmacy","Chemistry","Botany","Economics"],
    seats:"~4,000/year",
    established:1950,
    website:"uop.edu.pk",
    description:"KPK's top general university with a strong research culture. Renowned for its International Relations department.",
    highlights:["KPK #1 general uni","Strong IR department","Research culture","Affordable"],
    scholarships:"KPK govt + HEC",
    hostel:"Available"
  },
  {
    id:30, rank:30, name:"NCA", full:"National College of Arts",
    city:"Lahore", type:"public", icon:"🎨",
    tags:["public","arts"],
    fee:"Rs. 10–25K/sem", feeNum:18000,
    merit:"Portfolio + test",
    entry:"NCA Entry Test + Portfolio",
    programs:["Fine Arts","Graphic Design","Sculpture","Textile Design","Architecture","Film"],
    seats:"~300/year",
    established:1875,
    website:"nca.edu.pk",
    description:"Pakistan's #1 arts university (HEC ranked), established in 1875 — the oldest arts institution in the subcontinent. Located in Lahore.",
    highlights:["HEC #1 arts university","1875 — oldest","Pakistan's creative hub","Affordable"],
    scholarships:"Merit-based",
    hostel:"Limited",
    province:"Punjab"
  }
];

// ─── Province map for original 29 universities (NCA already has province) ───
const PROVINCE_MAP = {
  1:'Federal',2:'Punjab',3:'Punjab',4:'Sindh',5:'Federal',
  6:'Federal',7:'Federal',8:'KPK',9:'Federal',10:'Sindh',
  11:'Punjab',12:'Sindh',13:'Sindh',14:'Federal',15:'Federal',
  16:'Punjab',17:'Sindh',18:'Punjab',19:'Sindh',20:'Punjab',
  21:'Federal',22:'Punjab',23:'Federal',24:'Punjab',25:'Sindh',
  26:'Punjab',27:'Punjab',28:'Federal',29:'KPK'
};
UNIVERSITIES.forEach(u=>{if(!u.province&&PROVINCE_MAP[u.id])u.province=PROVINCE_MAP[u.id];});

// ─── Smart default programs based on university focus (name + tags) ───
function defaultPrograms(full, tg=[], ty=''){
  const s = (full||'').toLowerCase();
  const has = k => tg.includes(k);
  // 1. Specialised institutes detected by name keywords (highest priority)
  if(/(agricultur|\bvet|veterinary|animal|marine|water)/.test(s))
    return ['BS Agriculture','DVM (Veterinary Medicine)','BS Food Science & Technology',
            'BS Animal Sciences','BS Horticulture','BS Agronomy','BS Agricultural Engineering','BS Environmental Science'];
  if(/(fashion|design|art|architecture|culture|heritage)/.test(s) || has('arts'))
    return ['BS Fashion Design','BS Graphic Design','BFA (Fine Arts)','BS Interior Design',
            'BS Architecture','BS Textile Design','BS Visual Communication','BS Product Design'];
  if(/education/.test(s))
    return ['B.Ed','BS Education','M.Ed','BS English','BS Mathematics',
            'BS Islamic Studies','BS Special Education','BS Educational Psychology'];
  if(/(medical|health|nursing|dental)/.test(s) || has('medical'))
    return ['MBBS','BDS','Pharm-D','BS Nursing','DPT (Physiotherapy)',
            'BS Medical Lab Technology','BS Radiology','BS Human Nutrition'];
  if(/(engineering|technology|technical|polytechnic|power)/.test(s) || has('engineering'))
    return ['BS Electrical Engineering','BS Mechanical Engineering','BS Civil Engineering',
            'BS Computer Engineering','BS Software Engineering','BS Computer Science',
            'BS Electronics Engineering','BS Chemical Engineering'];
  if(/(business|economics|management|commerce|leadership)/.test(s) || has('business'))
    return ['BBA','MBA','BS Accounting & Finance','BS Economics','BS Commerce',
            'BS Business Analytics','BS Banking & Finance','BS Public Administration'];
  // 2. General university — broad standard offering
  return ['BS Computer Science','BBA','BS Software Engineering','BS English',
          'BS Mathematics','BS Economics','BS Information Technology','BS Psychology',
          'BS Sociology','BS Islamic Studies','BS Chemistry','BS Physics'];
}

// ─── mk() helper for HEC basic entries ───
function mk(id,n,f,c,ty,e,pv,tg=[]){
  return {id,rank:0,name:n,full:f,city:c,type:ty,
    icon:ty==='public'?'🏛️':ty==='military'?'⚔️':'🏢',
    tags:[ty,...tg,pv.toLowerCase().replace(/[\s/-]/g,'')],
    fee:'Check university website',feeNum:0,
    merit:'HEC Recognized',entry:'Check university website',
    programs:defaultPrograms(f,tg,ty),seats:'—',established:e,website:'',
    description:`${f} — HEC recognized ${ty} university in ${c}.`,
    highlights:['HEC Recognized'],
    scholarships:'Contact university',hostel:'Contact university',
    province:pv,basic:true};
}

// ─── 188 new HEC universities ───
UNIVERSITIES.push(
// FEDERAL
mk(31,'NDU','National Defence University','Islamabad','public',1970,'Federal'),
mk(32,'AIOU','Allama Iqbal Open University','Islamabad','public',1974,'Federal'),
mk(33,'VU','Virtual University of Pakistan','Online','public',2002,'Federal'),
mk(34,'CUST','Capital University of Science & Technology','Islamabad','private',1998,'Federal',['engineering']),
mk(35,'Riphah','Riphah International University','Islamabad','private',2002,'Federal',['medical']),
mk(36,'FUUAST','Federal Urdu University of Arts, Science & Technology','Karachi/Islamabad','public',1949,'Federal'),
mk(37,'FUI','Foundation University Islamabad','Islamabad','private',2002,'Federal'),
mk(38,'PIDE','Pakistan Institute of Development Economics','Islamabad','public',1957,'Federal',['business']),
mk(39,'Shifa','Shifa Tameer-e-Millat University','Islamabad','private',2012,'Federal',['medical']),
mk(40,'SZABMU','Shaheed Zulfiqar Ali Bhutto Medical University','Islamabad','public',2013,'Federal',['medical']),
mk(41,'NUTECH','National University of Technology','Islamabad','public',2018,'Federal',['engineering']),
mk(42,'NSU','National Skills University','Islamabad','public',2018,'Federal'),
mk(43,'CASE','Sir Syed CASE Institute of Technology','Islamabad','private',2001,'Federal',['engineering']),
mk(44,'IBADAT','IBADAT International University','Islamabad','private',1998,'Federal'),
mk(45,'MYU','Muslim Youth University','Islamabad','private',2013,'Federal'),
// PUNJAB — Lahore
mk(46,'LCWU','Lahore College for Women University','Lahore','public',1922,'Punjab'),
mk(47,'FJMU','Fatima Jinnah Medical University','Lahore','public',1941,'Punjab',['medical']),
mk(48,'KEMU','King Edward Medical University','Lahore','public',1860,'Punjab',['medical']),
mk(49,'UVAS','University of Veterinary & Animal Sciences','Lahore','public',1882,'Punjab'),
mk(50,'Kinnaird','Kinnaird College for Women University','Lahore','public',1913,'Punjab'),
mk(51,'UMT','University of Management & Technology','Lahore','private',1990,'Punjab',['business']),
mk(52,'UOL','University of Lahore','Lahore','private',1999,'Punjab'),
mk(53,'BNU','Beaconhouse National University','Lahore','private',2003,'Punjab',['arts']),
mk(54,'Minhaj','Minhaj University Lahore','Lahore','private',1986,'Punjab'),
mk(55,'Superior','Superior University','Lahore','private',2000,'Punjab'),
mk(56,'UOE','University of Education','Lahore','public',2002,'Punjab'),
mk(57,'Hajvery','Hajvery University','Lahore','private',2002,'Punjab'),
mk(58,'PIFD','Pakistan Institute of Fashion & Design','Lahore','public',1994,'Punjab',['arts']),
mk(59,'LSE','Lahore School of Economics','Lahore','public',1997,'Punjab',['business']),
mk(60,'LGU','Lahore Garrison University','Lahore','private',2010,'Punjab'),
mk(61,'UOHE','University of Home Economics','Lahore','public',1955,'Punjab'),
mk(62,'NCBA&E','National College of Business Administration & Economics','Lahore','private',1994,'Punjab',['business']),
mk(63,'USA','University of South Asia','Lahore','private',2003,'Punjab'),
mk(64,'IMS Lahore','Institute of Management Sciences Lahore','Lahore','private',1987,'Punjab',['business']),
mk(65,'IAC','Institute for Art and Culture','Lahore','public',2018,'Punjab',['arts']),
mk(66,'LLU','Lahore Leads University','Lahore','private',2001,'Punjab'),
mk(67,'Qarshi','Qarshi University','Lahore','private',2011,'Punjab'),
mk(68,'NUR','NUR International University','Lahore','private',2015,'Punjab'),
// PUNJAB — Rawalpindi
mk(69,'PMAS-AAUR','Pir Mehr Ali Shah Arid Agriculture University','Rawalpindi','public',1970,'Punjab'),
mk(70,'FJWU','Fatima Jinnah Women University','Rawalpindi','public',1998,'Punjab'),
mk(71,'RMU','Rawalpindi Medical University','Rawalpindi','public',1974,'Punjab',['medical']),
mk(72,'NUMS','National University of Medical Sciences','Rawalpindi','military',2015,'Punjab',['medical']),
mk(73,'RWU','Rawalpindi Women University','Rawalpindi','public',2019,'Punjab'),
// PUNJAB — Taxila
mk(74,'HITEC','HITEC University','Taxila','private',2007,'Punjab',['engineering']),
// PUNJAB — Faisalabad
mk(75,'UAF','University of Agriculture Faisalabad','Faisalabad','public',1906,'Punjab'),
mk(76,'GCUF','Government College University Faisalabad','Faisalabad','public',1897,'Punjab'),
mk(77,'NTU','National Textile University','Faisalabad','public',1959,'Punjab',['engineering']),
mk(78,'FMU','Faisalabad Medical University','Faisalabad','public',1973,'Punjab',['medical']),
mk(79,'GCWUF','Government College Women University Faisalabad','Faisalabad','public',2012,'Punjab'),
mk(80,'UOF','University of Faisalabad','Faisalabad','private',2002,'Punjab'),
// PUNJAB — Bahawalpur
mk(81,'IUB','Islamia University of Bahawalpur','Bahawalpur','public',1925,'Punjab'),
mk(82,'GSCWU','Government Sadiq College Women University','Bahawalpur','public',2012,'Punjab'),
mk(83,'CUVAS','Cholistan University of Vet & Animal Sciences','Bahawalpur','public',2014,'Punjab'),
// PUNJAB — Multan
mk(84,'WUM','Women University Multan','Multan','public',2010,'Punjab'),
mk(85,'USP','University of Southern Punjab','Multan','private',2010,'Punjab'),
mk(86,'NMU','Nishtar Medical University','Multan','public',1951,'Punjab',['medical']),
mk(87,'NFC-IET','NFC Institute of Engineering & Technology','Multan','public',1985,'Punjab',['engineering']),
mk(88,'MNS-UA','Muhammad Nawaz Sharif University of Agriculture','Multan','public',2012,'Punjab'),
mk(89,'MNS-UET','MNS University of Engineering & Technology','Multan','public',2012,'Punjab',['engineering']),
mk(90,'Times','Times Institute','Multan','private',2008,'Punjab'),
mk(91,'Emerson','Emerson University','Multan','public',1920,'Punjab'),
// PUNJAB — Other cities
mk(92,'UOS','University of Sargodha','Sargodha','public',1916,'Punjab'),
mk(93,'GIFT','GIFT University','Gujranwala','private',2002,'Punjab',['business']),
mk(94,'UOG','University of Gujrat','Gujrat','public',2004,'Punjab'),
mk(95,'USKT','University of Sialkot','Sialkot','private',2013,'Punjab'),
mk(96,'GCWUS','Government College Women University Sialkot','Sialkot','public',2012,'Punjab'),
mk(97,'Namal','Namal University','Mianwali','private',2008,'Punjab'),
mk(98,'UOM','University of Mianwali','Mianwali','public',2012,'Punjab'),
mk(99,'UOO','University of Okara','Okara','public',2015,'Punjab'),
mk(100,'UOSA','University of Sahiwal','Sahiwal','public',2015,'Punjab'),
mk(101,'UOJ','University of Jhang','Jhang','public',2015,'Punjab'),
mk(102,'GU','Ghazi University','DG Khan','public',2012,'Punjab'),
mk(103,'KFUEIT','Khawaja Fareed University of Engineering & IT','Rahim Yar Khan','public',2014,'Punjab',['engineering']),
mk(104,'UON','University of Narowal','Narowal','public',2018,'Punjab'),
mk(105,'UOC','University of Chakwal','Chakwal','public',2020,'Punjab'),
mk(106,'UOLayyah','University of Layyah','Layyah','public',2009,'Punjab'),
mk(107,'KUM','Kohsar University Murree','Murree','public',2020,'Punjab'),
mk(108,'TU','Thal University','Bhakkar','public',2022,'Punjab'),
mk(109,'AQU','Al-Qadir University','Sohawa','public',2021,'Punjab'),
mk(110,'BGNU','Baba Guru Nanak University','Nankana Sahib','public',2021,'Punjab'),
mk(111,'PTUTT','Punjab Tianjin University of Technology','Lahore','public',2018,'Punjab',['engineering']),
mk(112,'UOW','University of Wah','Wah Cantt','private',2005,'Punjab'),
mk(113,'PUTR','Punjab University of Technology Rasul','Mandi Bahauddin','public',1873,'Punjab',['engineering']),
// SINDH — Karachi
mk(114,'UOK','University of Karachi','Karachi','public',1951,'Sindh'),
mk(115,'SSUET','Sir Syed University of Engineering & Technology','Karachi','private',1993,'Sindh',['engineering']),
mk(116,'IVS','Indus Valley School of Art & Architecture','Karachi','private',1989,'Sindh',['arts']),
mk(117,'Hamdard','Hamdard University','Karachi','private',1991,'Sindh',['medical']),
mk(118,'JSMU','Jinnah Sindh Medical University','Karachi','public',1973,'Sindh',['medical']),
mk(119,'Baqai','Baqai Medical University','Karachi','private',1989,'Sindh',['medical']),
mk(120,'DHA Suffa','DHA Suffa University','Karachi','private',2002,'Sindh'),
mk(121,'Ziauddin','Ziauddin University','Karachi','private',1986,'Sindh',['medical']),
mk(122,'IoBM','Institute of Business Management','Karachi','private',1995,'Sindh',['business']),
mk(123,'Iqra','Iqra University','Karachi','private',1998,'Sindh',['business']),
mk(124,'DUET','Dawood University of Engineering & Technology','Karachi','public',1962,'Sindh',['engineering']),
mk(125,'Greenwich','Greenwich University','Karachi','private',1987,'Sindh'),
mk(126,'MAJU','Muhammad Ali Jinnah University','Karachi','private',1998,'Sindh'),
mk(127,'KIET','Karachi Institute of Economics & Technology','Karachi','private',1997,'Sindh',['business']),
mk(128,'SMIU','Sindh Madressatul Islam University','Karachi','public',1885,'Sindh'),
mk(129,'JUW','Jinnah University for Women','Karachi','private',1998,'Sindh'),
mk(130,'Dadabhoy','Dadabhoy Institute of Higher Education','Karachi','private',2000,'Sindh'),
mk(131,'Ilma','Ilma University','Karachi','private',2001,'Sindh'),
mk(132,'Indus','Indus University','Karachi','private',2004,'Sindh'),
mk(133,'KSBL','Karachi School for Business & Leadership','Karachi','private',2009,'Sindh',['business']),
mk(134,'SHU','Salim Habib University','Karachi','private',2015,'Sindh'),
mk(135,'SBBCU','Shaheed Benazir Bhutto City University','Karachi','public',2013,'Sindh'),
mk(136,'CUHS','City University of Health Sciences','Karachi','public',1991,'Sindh',['medical']),
mk(137,'Newports','Newports Institute of Communications & Economics','Karachi','private',2013,'Sindh'),
mk(138,'PNA','Pakistan Naval Academy','Karachi','military',1970,'Sindh'),
mk(139,'KINPOE','Karachi Institute of Power Engineering','Karachi','public',1993,'Sindh',['engineering']),
mk(140,'Malir','Malir University of Science & Technology','Karachi','private',2017,'Sindh'),
mk(141,'BBSU','Benazir Bhutto Shaheed University','Karachi','public',2010,'Sindh'),
// SINDH — Interior
mk(142,'USindh','University of Sindh','Jamshoro','public',1947,'Sindh'),
mk(143,'LUMHS','Liaquat University of Medical & Health Sciences','Jamshoro','public',1881,'Sindh',['medical']),
mk(144,'GCUH','Government College University Hyderabad','Hyderabad','public',1917,'Sindh'),
mk(145,'Isra','Isra University','Hyderabad','private',1997,'Sindh',['medical']),
mk(146,'SAU','Sindh Agriculture University','Tandojam','public',1939,'Sindh'),
mk(147,'SIBAUK','Sukkur IBA University','Sukkur','public',1994,'Sindh',['business']),
mk(148,'SALU','Shah Abdul Latif University','Khairpur','public',1974,'Sindh'),
mk(149,'QUEST','Quaid-e-Awam University of Engineering S&T','Nawabshah','public',1974,'Sindh',['engineering']),
mk(150,'SBBU','Shaheed Benazir Bhutto University Benazirabad','Benazirabad','public',2010,'Sindh'),
mk(151,'PUMHS','Peoples University of Medical & Health Sciences','Nawabshah','public',2013,'Sindh',['medical']),
mk(152,'SBBUVS','SBB University of Veterinary Sciences','Sakrand','public',2012,'Sindh'),
mk(153,'SBBMUL','SBB Medical University Larkana','Larkana','public',2008,'Sindh',['medical']),
mk(154,'USMS','University of Sufism and Modern Sciences','Bhit Shah','public',2011,'Sindh'),
mk(155,'SAYUni','Shaikh Ayaz University','Shikarpur','public',2011,'Sindh'),
mk(156,'Aror','Aror University of Art, Architecture & Heritage','Sukkur','public',2013,'Sindh',['arts']),
mk(157,'BNBWU','Begum Nusrat Bhutto Women University','Sukkur','public',2018,'Sindh'),
mk(158,'SABSUA','Shaheed Allah Bux Soomro University of Art & Design','Khairpur','public',1990,'Sindh',['arts']),
// KPK
mk(159,'ICU','Islamia College University','Peshawar','public',1913,'KPK'),
mk(160,'UETPESHAWAR','University of Engineering & Technology Peshawar','Peshawar','public',1952,'KPK',['engineering']),
mk(161,'KMU','Khyber Medical University','Peshawar','public',2007,'KPK',['medical']),
mk(162,'IMSciences','Institute of Management Sciences Peshawar','Peshawar','public',1995,'KPK',['business']),
mk(163,'SBBWU','Shaheed Benazir Bhutto Women University Peshawar','Peshawar','public',2005,'KPK'),
mk(164,'CECOS','CECOS University','Peshawar','private',1986,'KPK',['engineering']),
mk(165,'Gandhara','Gandhara University','Peshawar','private',1995,'KPK',['medical']),
mk(166,'Sarhad','Sarhad University of Science & IT','Peshawar','private',2001,'KPK'),
mk(167,'CUI-KPK','City University of Science & IT Peshawar','Peshawar','private',2001,'KPK'),
mk(168,'Abasyn','Abasyn University','Peshawar','private',2007,'KPK'),
mk(169,'Qurtuba','Qurtuba University','DI Khan','private',2001,'KPK'),
mk(170,'Gomal','Gomal University','DI Khan','public',1974,'KPK'),
mk(171,'UAPESHAWAR','University of Agriculture Peshawar','Peshawar','public',1981,'KPK'),
mk(172,'UOM','University of Malakand','Chakdara','public',2001,'KPK'),
mk(173,'USWAT','University of Swat','Swat','public',2010,'KPK'),
mk(174,'USWABI','University of Swabi','Swabi','public',2012,'KPK'),
mk(175,'HU','Hazara University','Mansehra','public',2002,'KPK'),
mk(176,'AUST','Abbottabad University of Science & Technology','Havelian','public',2008,'KPK'),
mk(177,'KUST','Kohat University of Science & Technology','Kohat','public',2001,'KPK'),
mk(178,'UOH','University of Haripur','Haripur','public',2012,'KPK'),
mk(179,'AWKUM','Abdul Wali Khan University Mardan','Mardan','public',2009,'KPK'),
mk(180,'WUM-KPK','Women University Mardan','Mardan','public',2016,'KPK'),
mk(181,'UETMARDAN','University of Engineering & Technology Mardan','Mardan','public',2018,'KPK',['engineering']),
mk(182,'BKU','Bacha Khan University','Charsadda','public',2012,'KPK'),
mk(183,'USTB','University of Science & Technology Bannu','Bannu','public',2005,'KPK'),
mk(184,'WUSWABI','Women University Swabi','Swabi','public',2016,'KPK'),
mk(185,'KKKUK','Khushal Khan Khattak University','Karak','public',2012,'KPK'),
mk(186,'SBBUSH','Shaheed Benazir Bhutto University Sheringal','Upper Dir','public',2009,'KPK'),
mk(187,'UBUNER','University of Buner','Buner','public',2012,'KPK'),
mk(188,'UTN','University of Technology Nowshera','Nowshera','public',2015,'KPK'),
mk(189,'FATA','FATA University','Akhorwal','public',2016,'KPK'),
mk(190,'UOChitral','University of Chitral','Chitral','public',2017,'KPK'),
mk(191,'UOLM','University of Lakki Marwat','Lakki Marwat','public',2017,'KPK'),
mk(192,'UODir','University of Dir','Timergara','public',2021,'KPK'),
mk(193,'UOShangla','University of Shangla','Shangla','public',2022,'KPK'),
mk(194,'PAAAS','Pak-Austria Institute of Applied Sciences','Haripur','public',2020,'KPK'),
mk(195,'INU','IQRA National University Peshawar','Peshawar','private',2000,'KPK'),
mk(196,'NUN','Northern University Nowshera','Nowshera','private',2002,'KPK'),
mk(197,'UADIK','University of Agriculture DI Khan','DI Khan','public',2018,'KPK'),
// BALOCHISTAN
mk(198,'UOB','University of Balochistan','Quetta','public',1970,'Balochistan'),
mk(199,'BUMHS','Bolan University of Medical & Health Sciences','Quetta','public',1972,'Balochistan',['medical']),
mk(200,'BUITEMS','Balochistan University of IT, Engineering & Management Sciences','Quetta','public',2002,'Balochistan',['engineering']),
mk(201,'SBKWU','Sardar Bahadur Khan Women\'s University','Quetta','public',2004,'Balochistan'),
mk(202,'UOTUR','University of Turbat','Turbat','public',2012,'Balochistan'),
mk(203,'UOGWD','University of Gwadar','Gwadar','public',2016,'Balochistan'),
mk(204,'UOMak','University of Makran','Panjgur','public',2022,'Balochistan'),
mk(205,'BUET','Balochistan University of Engineering & Technology','Khuzdar','public',1987,'Balochistan',['engineering']),
mk(206,'LUAWMS','Lasbela University of Agriculture, Water & Marine Sciences','Lasbela','public',2005,'Balochistan'),
mk(207,'UOLOR','University of Loralai','Loralai','public',2009,'Balochistan'),
mk(208,'MCKRU','Mir Chakar Khan Rind University','Sibi','public',2019,'Balochistan'),
mk(209,'AHIU','Al-Hamd Islamic University','Quetta','private',1995,'Balochistan'),
// AJK
mk(210,'MUST','Mirpur University of Science & Technology','Mirpur','public',1980,'AJK',['engineering']),
mk(211,'UAJK','University of Azad Jammu & Kashmir','Muzaffarabad','public',1980,'AJK'),
mk(212,'UOPOONCH','University of Poonch Rawalakot','Rawalakot','public',1980,'AJK'),
mk(213,'AlKhair','Al-Khair University','Mirpur','private',1994,'AJK'),
mk(214,'MDIU','Mohi-ud-Din Islamic University','Nerian Sharif','private',2000,'AJK'),
mk(215,'WUAJK','Women University of AJK Bagh','Bagh','public',2013,'AJK'),
mk(216,'UOKOTLI','University of Kotli','Kotli','public',2014,'AJK'),
// GILGIT-BALTISTAN
mk(217,'KIU','Karakoram International University','Gilgit','public',2002,'Gilgit-Baltistan'),
mk(218,'BU','Baltistan University','Skardu','public',2017,'Gilgit-Baltistan')
);

// ─── Website map for 188 basic HEC universities ───
const WEBSITE_MAP = {
  // Federal
  31:'ndu.edu.pk',32:'aiou.edu.pk',33:'vu.edu.pk',34:'cust.edu.pk',
  35:'riphah.edu.pk',36:'fuuast.edu.pk',37:'fui.edu.pk',38:'pide.org.pk',
  39:'shifa.edu.pk',40:'szabmu.edu.pk',41:'nutech.edu.pk',42:'nsu.edu.pk',
  43:'case.edu.pk',44:'ibadat.edu.pk',45:'myu.edu.pk',
  // Punjab - Lahore
  46:'lcwu.edu.pk',47:'fjmu.edu.pk',48:'kemu.edu.pk',49:'uvas.edu.pk',
  50:'kinnaird.edu.pk',51:'umt.edu.pk',52:'uol.edu.pk',53:'bnu.edu.pk',
  54:'minhaj.edu.pk',55:'superior.edu.pk',56:'ue.edu.pk',57:'hajvery.edu.pk',
  58:'pifd.edu.pk',59:'lahoreschoolofeconomics.edu.pk',60:'lgu.edu.pk',
  61:'uohe.edu.pk',62:'ncbae.edu.pk',63:'southasia.edu.pk',64:'imscienceslahore.edu.pk',
  65:'iac.edu.pk',66:'leads.edu.pk',67:'qarshi.edu.pk',68:'nur.edu.pk',
  // Punjab - Rawalpindi / Attock
  69:'uaar.edu.pk',70:'fjwu.edu.pk',71:'rmu.edu.pk',72:'nums.edu.pk',73:'rwu.edu.pk',
  // Punjab - Taxila / Wah
  74:'hitecuni.edu.pk',112:'uow.edu.pk',113:'putr.edu.pk',
  // Punjab - Faisalabad
  75:'uaf.edu.pk',76:'gcuf.edu.pk',77:'ntu.edu.pk',78:'fmu.edu.pk',
  79:'gcwuf.edu.pk',80:'tuf.edu.pk',
  // Punjab - Bahawalpur
  81:'iub.edu.pk',82:'gscwu.edu.pk',83:'cuvas.edu.pk',
  // Punjab - Multan
  84:'wum.edu.pk',85:'usp.edu.pk',86:'nmu.edu.pk',87:'nfc-iet.edu.pk',
  88:'mnsuam.edu.pk',89:'mnsuet.edu.pk',90:'timesinstitute.edu.pk',91:'emerson.edu.pk',
  // Punjab - Sargodha / Gujranwala / Sialkot / Mianwali
  92:'uos.edu.pk',93:'gift.edu.pk',94:'uog.edu.pk',95:'uskt.edu.pk',
  96:'gcwus.edu.pk',97:'namal.edu.pk',98:'umianwali.edu.pk',99:'uookara.edu.pk',
  100:'uosaghiwal.edu.pk',101:'ujhang.edu.pk',102:'ghaziuniversity.edu.pk',
  103:'kfueit.edu.pk',104:'unarowal.edu.pk',105:'uochakwal.edu.pk',
  106:'ulayyah.edu.pk',107:'kum.edu.pk',108:'thaluniversity.edu.pk',
  109:'alqadiruniversity.edu.pk',110:'bgnu.edu.pk',111:'ptutt.edu.pk',
  // Sindh - Karachi
  114:'uok.edu.pk',115:'ssuet.edu.pk',116:'ivs.edu.pk',117:'hamdard.edu.pk',
  118:'jsmu.edu.pk',119:'baqai.edu.pk',120:'dsu.edu.pk',121:'zu.edu.pk',
  122:'iobm.edu.pk',123:'iqra.edu.pk',124:'duet.edu.pk',125:'greenwich.edu.pk',
  126:'jinnah.edu.pk',127:'kiet.edu.pk',128:'smiu.edu.pk',129:'juw.edu.pk',
  130:'dadabhoy.edu.pk',131:'ilmauniversity.edu.pk',132:'indus.edu.pk',
  133:'ksbl.edu.pk',134:'shu.edu.pk',135:'sbbcu.edu.pk',136:'cuhs.edu.pk',
  137:'newports.edu.pk',138:'pna.edu.pk',139:'kinpoe.edu.pk',140:'malir.edu.pk',
  141:'bbsul.edu.pk',
  // Sindh - Interior
  142:'usindh.edu.pk',143:'lumhs.edu.pk',144:'gcuh.edu.pk',145:'isra.edu.pk',
  146:'sau.edu.pk',147:'iba-suk.edu.pk',148:'salu.edu.pk',149:'quest.edu.pk',
  150:'sbbu.edu.pk',151:'pumhs.edu.pk',152:'sbbuvs.edu.pk',153:'sbbmul.edu.pk',
  154:'usms.edu.pk',155:'shaikhayaz.edu.pk',156:'aror.edu.pk',157:'bnbwu.edu.pk',
  158:'sabsua.edu.pk',
  // KPK - Peshawar
  159:'icp.edu.pk',160:'uetpeshawar.edu.pk',161:'kmu.edu.pk',162:'imsciences.edu.pk',
  163:'sbbwup.edu.pk',164:'cecos.edu.pk',165:'gandhara.edu.pk',166:'sarhad.edu.pk',
  167:'cityuniversity.edu.pk',168:'abasyn.edu.pk',
  // KPK - DI Khan / Gomal
  169:'qurtuba.edu.pk',170:'gu.edu.pk',
  // KPK - Agriculture / Malakand / Swat / Hazara
  171:'aup.edu.pk',172:'uom.edu.pk',173:'uswat.edu.pk',174:'uswabi.edu.pk',
  175:'hu.edu.pk',176:'aust.edu.pk',177:'kust.edu.pk',178:'uoh.edu.pk',
  // KPK - Mardan / Charsadda / Bannu / Others
  179:'awkum.edu.pk',180:'wumardan.edu.pk',181:'uetmardan.edu.pk',182:'bkuc.edu.pk',
  183:'ustb.edu.pk',184:'wuswabi.edu.pk',185:'kkkuk.edu.pk',186:'sbbush.edu.pk',
  187:'ubuner.edu.pk',188:'utn.edu.pk',189:'fatauniversity.edu.pk',
  190:'uochitral.edu.pk',191:'uolm.edu.pk',192:'uodir.edu.pk',193:'uoshangla.edu.pk',
  194:'paf-iast.edu.pk',195:'inu.edu.pk',196:'northern.edu.pk',197:'uoadik.edu.pk',
  // Balochistan
  198:'uob.edu.pk',199:'bumhs.edu.pk',200:'buitms.edu.pk',201:'sbkwu.edu.pk',
  202:'uot.edu.pk',203:'uogwadar.edu.pk',204:'umakran.edu.pk',205:'buetk.edu.pk',
  206:'luawms.edu.pk',207:'uolor.edu.pk',208:'mckru.edu.pk',209:'alhamd.edu.pk',
  // AJK
  210:'must.edu.pk',211:'ajku.edu.pk',212:'upr.edu.pk',213:'al-khair.edu.pk',
  214:'miuazad.edu.pk',215:'wuajkbagh.edu.pk',216:'uokotli.edu.pk',
  // Gilgit-Baltistan
  217:'kiu.edu.pk',218:'baltistanuniversity.edu.pk'
};
UNIVERSITIES.forEach(u=>{ if(!u.website && WEBSITE_MAP[u.id]) u.website=WEBSITE_MAP[u.id]; });

// ─── Data updates for top 50 well-known universities (approx. 2024-25) ───
const DATA_UPDATES = {
  // ── FEDERAL ──
  32:{ fee:'Rs. 5–15K/sem', feeNum:10000, merit:'Open Enrollment', entry:'No entry test',
    programs:['BA','BSc','B.Ed','BBA','MBA','MA','MSc','MPhil','PhD'],
    description:'Allama Iqbal Open University (AIOU) is Pakistan\'s largest distance-learning institution, founded in 1974. With over 1.3 million enrolled students, it offers flexible education from matric to PhD level across all four provinces.',
    highlights:['1.3M+ Students','Distance Learning','Countrywide Reach','Affordable Fees'],
    scholarships:'Need-based & merit scholarships available', hostel:'Not applicable (distance learning)' },
  33:{ fee:'Rs. 8–20K/sem', feeNum:14000, merit:'Merit-based (previous grades)', entry:'No entry test',
    programs:['BS CS','BS IT','BBA','MBA','BS Math','BS English','BS Commerce'],
    description:'Virtual University of Pakistan (VU) is the country\'s first public online university, established in 2002. It delivers HEC-recognized degrees entirely through e-learning, making quality education accessible from anywhere in Pakistan.',
    highlights:['100% Online','Affordable','HEC Recognized','No Entry Test'],
    scholarships:'Need-based scholarships via HEC', hostel:'Not applicable (online university)' },
  34:{ fee:'Rs. 60–100K/sem', feeNum:80000, merit:'70%+ in FSc', entry:'CUST Entry Test',
    programs:['BS CS','BS SE','BS EE','BBA','MBA','BS Telecom'],
    description:'Capital University of Science & Technology (CUST) is a private HEC-recognized university in Islamabad, known for strong engineering and IT programs with modern labs and industry linkages.',
    highlights:['Engineering Focus','Modern Labs','Industry Links','Islamabad Campus'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  35:{ fee:'Rs. 80–150K/sem', feeNum:115000, merit:'65%+ in FSc', entry:'Riphah Entry Test',
    programs:['MBBS','DPT','Pharmacy','BS Nursing','BBA','BS CS','Islamic Studies'],
    description:'Riphah International University is a private university in Islamabad offering programs in medical, engineering, and Islamic studies. It is known for integrating Islamic values with modern education.',
    highlights:['Medical & Islamic Studies','Modern Facilities','Multiple Campuses','HEC W-Category'],
    scholarships:'Merit, need-based & Islamic studies scholarships', hostel:'Separate hostels for males & females' },
  41:{ fee:'Rs. 40–70K/sem', feeNum:55000, merit:'60%+ in FSc Pre-Engineering', entry:'NUTECH Entry Test',
    programs:['BS Civil Eng','BS Electrical Eng','BS Mechanical Eng','BS CS','BS SE'],
    description:'National University of Technology (NUTECH) is a public university in Islamabad established in 2018, offering engineering and technology programs with strong industrial collaboration.',
    highlights:['Public University','Engineering Focus','Industry Collaboration','New Campus'],
    scholarships:'HEC need-based & merit scholarships', hostel:'Available on campus' },
  72:{ fee:'Rs. 60–120K/sem', feeNum:90000, merit:'Army/NUMS Merit List', entry:'NUMS Entry Test / MDCAT',
    programs:['MBBS','BDS','Doctor of Pharmacy','DPT','BS Nursing','Allied Health'],
    description:'National University of Medical Sciences (NUMS) Rawalpindi is a military-affiliated medical university. It is ranked among Pakistan\'s top medical institutions with state-of-the-art facilities and teaching hospitals.',
    highlights:['Military Affiliation','Top Medical University','Teaching Hospitals','State-of-art Labs'],
    scholarships:'Military & merit-based scholarships', hostel:'Well-equipped hostels available' },

  // ── PUNJAB – LAHORE ──
  46:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'60%+ in Intermediate', entry:'LCWU Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS IT','BS Education','BS Fashion Design','MA','MSc'],
    description:'Lahore College for Women University (LCWU) is one of Pakistan\'s oldest and most prestigious women\'s universities, founded in 1922. It offers a wide range of undergraduate and postgraduate programs in a safe and academic environment.',
    highlights:['Women\'s University','100+ Years Heritage','Large Campus','Affordable Fees'],
    scholarships:'Merit, need-based & provincial scholarships', hostel:'On-campus hostel available' },
  47:{ fee:'Rs. 50–80K/sem', feeNum:65000, merit:'85%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BDS','DPT','Allied Health Sciences'],
    description:'Fatima Jinnah Medical University (FJMU) Lahore, formerly Fatima Jinnah Medical College, is one of the oldest and most respected women\'s medical colleges in Pakistan, established in 1948.',
    highlights:['Top Medical College','Women\'s University','150+ Years Heritage','Teaching Hospital'],
    scholarships:'Government & merit-based scholarships', hostel:'On-campus hostel for females' },
  48:{ fee:'Rs. 60–100K/sem', feeNum:80000, merit:'85%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BDS','DPT','Allied Health Sciences','Doctor of Pharmacy'],
    description:'King Edward Medical University (KEMU) Lahore is one of the most prestigious medical universities in South Asia, established in 1860. Affiliated with Mayo Hospital, it consistently produces top-ranking doctors.',
    highlights:['165+ Years Heritage','Top Ranking Medical','Affiliated Mayo Hospital','Highly Competitive'],
    scholarships:'Government scholarships & need-based aid', hostel:'Separate hostels for males & females' },
  49:{ fee:'Rs. 25–45K/sem', feeNum:35000, merit:'60%+ in FSc (Pre-Medical)', entry:'UVAS Entry Test',
    programs:['DVM','BS Animal Sciences','BS Food Sciences','BS Bioinformatics','BS Zoology','MPhil','PhD'],
    description:'University of Veterinary & Animal Sciences (UVAS) Lahore is a leading public institution for veterinary, animal, and food sciences in Pakistan, established in 1882. It is the premier institution for DVM programs in Punjab.',
    highlights:['Pakistan\'s Top Vet University','140+ Years Heritage','Research Excellence','Teaching Hospitals'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  50:{ fee:'Rs. 30–60K/sem', feeNum:45000, merit:'60%+ in Intermediate', entry:'Kinnaird Entry Test',
    programs:['BS Sciences','BS Social Sciences','BS Business','BS Arts','MA','MSc'],
    description:'Kinnaird College for Women University Lahore is a prestigious private women\'s institution, founded in 1913 by the Church of Scotland. It is one of Pakistan\'s most respected colleges for liberal arts and sciences.',
    highlights:['Women\'s University','110+ Years Heritage','International Affiliation','Lahore Campus'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  51:{ fee:'Rs. 80–150K/sem', feeNum:115000, merit:'65%+ in FSc', entry:'UMT Entry Test',
    programs:['BBA','MBA','BS CS','BS SE','BS EE','BS Civil Eng','BS Architecture','BS Law'],
    description:'University of Management & Technology (UMT) Lahore is a leading private university known for strong business and engineering programs, industry partnerships, and modern research facilities.',
    highlights:['Business & Engineering','Industry Links','Modern Facilities','Multiple Programs'],
    scholarships:'Merit, need-based & departmental scholarships', hostel:'On-campus hostel available' },
  52:{ fee:'Rs. 60–120K/sem', feeNum:90000, merit:'60%+ in FSc', entry:'UOL Entry Test',
    programs:['MBBS','BDS','BS Engineering','BBA','MBA','BS CS','BS Nursing','BS Allied Health'],
    description:'University of Lahore (UOL) is a large private university offering diverse programs including medical, engineering, and business. It has multiple campuses across Pakistan.',
    highlights:['Diverse Programs','Medical College','Multiple Campuses','Large University'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  55:{ fee:'Rs. 50–100K/sem', feeNum:75000, merit:'60%+ in Intermediate', entry:'Superior Entry Test',
    programs:['BBA','MBA','BS CS','BS SE','BS EE','BS Civil','BS Law','BS Psychology'],
    description:'Superior University Lahore is a well-known private university offering programs in business, engineering, IT, and social sciences with modern facilities and strong alumni network.',
    highlights:['Modern Campus','Strong Alumni','Multiple Programs','Industry Connections'],
    scholarships:'Merit & sports scholarships', hostel:'On-campus hostel available' },
  59:{ fee:'Rs. 30–65K/sem', feeNum:47000, merit:'65%+ in Intermediate', entry:'LSE Entry Test',
    programs:['BS Economics','BBA','MBA','BS Finance','BS Accounting','MA Economics','MPhil'],
    description:'Lahore School of Economics (LSE) is a public sector institution established in 1997, recognized as one of Pakistan\'s leading centers for economics and business education with strong research output.',
    highlights:['Economics Focused','Research Excellence','Lahore Campus','Public Sector'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },

  // ── PUNJAB – RAWALPINDI / ATTOCK ──
  69:{ fee:'Rs. 20–40K/sem', feeNum:30000, merit:'55%+ in FSc', entry:'PMAS-AAUR Entry Test',
    programs:['BS Agriculture','BS Horticulture','BS Food Tech','BS IT','BS Engineering','DVM','MPhil','PhD'],
    description:'Pir Mehr Ali Shah Arid Agriculture University (PMAS-AAUR) Rawalpindi is a public agriculture university established in 1970, specializing in arid zone agriculture, water conservation, and rural development.',
    highlights:['Agriculture Specialist','Research Excellence','Arid Zone Focus','Public University'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  70:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'FJWU Entry Test',
    programs:['BS Sciences','BS Social Sciences','BS IT','BS Business','BS Education','MA','MSc'],
    description:'Fatima Jinnah Women University (FJWU) Rawalpindi is a public women\'s university established in 1998, named after the Mother of the Nation. It provides quality higher education to women across Rawalpindi and surrounding areas.',
    highlights:['Women\'s University','Public Sector','Rawalpindi Campus','Affordable Fees'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  71:{ fee:'Rs. 50–80K/sem', feeNum:65000, merit:'80%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BS Nursing','DPT','Allied Health Sciences'],
    description:'Rawalpindi Medical University (RMU), formerly Rawalpindi Medical College, is one of Pakistan\'s oldest medical institutions established in 1974. It is affiliated with Holy Family Hospital and Benazir Bhutto Hospital.',
    highlights:['Public Medical University','Teaching Hospitals','Rawalpindi Campus','Competitive Merit'],
    scholarships:'Government & merit-based scholarships', hostel:'Separate hostels available' },

  // ── PUNJAB – FAISALABAD ──
  75:{ fee:'Rs. 20–40K/sem', feeNum:30000, merit:'55%+ in FSc', entry:'UAF Entry Test',
    programs:['BS Agriculture','DVM','BS Food Sciences','BS Horticulture','BS Agri Engineering','MPhil','PhD'],
    description:'University of Agriculture Faisalabad (UAF) is one of Pakistan\'s top agricultural universities, established in 1906. It is a leading research institution in food security, crop sciences, and veterinary medicine with nine faculties.',
    highlights:['120+ Years Heritage','Top Agriculture Uni','9 Faculties','Research Excellence'],
    scholarships:'Merit, need-based & HEC scholarships', hostel:'Well-equipped hostels available' },
  76:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'GCUF Entry Test',
    programs:['BS Sciences','BS Commerce','BS Arts','BS IT','BS Engineering','MA','MSc','MPhil','PhD'],
    description:'Government College University Faisalabad (GCUF) is a historic public university, tracing its origins to 1897. It offers a wide range of programs across sciences, humanities, and engineering with affordable public sector fees.',
    highlights:['125+ Years Heritage','Affordable Fees','Public University','Multiple Programs'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  77:{ fee:'Rs. 25–50K/sem', feeNum:37000, merit:'60%+ in FSc', entry:'NTU Entry Test / NET',
    programs:['BS Textile Engineering','BS Textile Design','BS Fashion Design','BS Textile Management','MPhil','PhD'],
    description:'National Textile University (NTU) Faisalabad is Pakistan\'s only specialized textile university, established in 1959. It is the country\'s premier institution for textile engineering, design, and management education.',
    highlights:['Pakistan\'s Only Textile Uni','Specialized Programs','Industry Links','Research Excellence'],
    scholarships:'Merit & industry scholarships', hostel:'On-campus hostel available' },
  81:{ fee:'Rs. 15–35K/sem', feeNum:25000, merit:'55%+ in Intermediate', entry:'IUB Entry Test / NTS',
    programs:['BS Engineering','BS Sciences','BS Commerce','Islamic Studies','BS IT','BS Social Sciences','LLB','MPhil','PhD'],
    description:'Islamia University of Bahawalpur (IUB) is one of Pakistan\'s oldest universities, founded in 1925. It has a rich heritage combining Islamic education with modern sciences, and serves thousands of students from southern Punjab.',
    highlights:['100+ Years Heritage','Islamic Heritage','Southern Punjab','Multiple Programs'],
    scholarships:'Merit, need-based & religious scholarships', hostel:'On-campus hostel available' },

  // ── PUNJAB – OTHERS ──
  91:{ fee:'Rs. 15–25K/sem', feeNum:20000, merit:'55%+ in Intermediate', entry:'NTS / Emerson Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS Education','MA','MSc'],
    description:'Emerson University Multan, formerly Emerson College, is a historic public institution established in 1920. Named after a British education commissioner, it offers diverse undergraduate and graduate programs in Multan.',
    highlights:['100+ Years Heritage','Public University','Multan Campus','Affordable Fees'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  92:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'UOS Entry Test',
    programs:['BS Sciences','BS Agriculture','BS Pharmacy','BS Engineering','BS IT','BS Social Sciences','LLB','MPhil','PhD'],
    description:'University of Sargodha (UOS) is a comprehensive public university with 216+ degree programs across 8 faculties and 3 campuses. It serves students from Sargodha, Bhakkar, Mianwali, and Khushab districts.',
    highlights:['216+ Programs','3 Campuses','Public University','Research Focus'],
    scholarships:'Merit & need-based scholarships', hostel:'Separate hostels available' },
  94:{ fee:'Rs. 15–35K/sem', feeNum:25000, merit:'55%+ in Intermediate', entry:'UOG Entry Test',
    programs:['BS Engineering','BS IT','BS Sciences','BS Arts','BS Business','BS Architecture','MPhil','PhD'],
    description:'University of Gujrat (UOG) is a public university established in 2004, offering 120+ degree programs across 7 faculties. With 16,000+ students and a modern campus, it is one of Punjab\'s fastest growing universities.',
    highlights:['120+ Programs','16K+ Students','Modern Campus','Public University'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  97:{ fee:'Rs. 50–100K/sem', feeNum:75000, merit:'70%+ in FSc', entry:'Namal NAT / Entry Test',
    programs:['BS CS','BS SE','BS Electrical Eng','BS Business Analytics','BS Economics','BBA'],
    description:'Namal University Mianwali is a unique private university affiliated with the University of Bradford (UK), founded by Imran Khan in 2008. It offers internationally recognized degrees with a focus on STEM and business in a modern campus setting.',
    highlights:['Bradford UK Affiliation','International Degrees','Modern Campus','STEM Focus'],
    scholarships:'Generous need-based & merit scholarships (many full scholarships)', hostel:'On-campus hostel available' },
  103:{ fee:'Rs. 25–50K/sem', feeNum:37000, merit:'60%+ in FSc Pre-Engineering', entry:'ETEA / KFUEIT Test',
    programs:['BS CS','BS SE','BS EE','BS Civil Eng','BS Mechanical Eng','BS IT','BBA'],
    description:'Khawaja Fareed University of Engineering & IT (KFUEIT) Rahim Yar Khan is a public engineering university established in 2014 to serve southern Punjab. It offers modern engineering programs with focus on regional development.',
    highlights:['Engineering Focused','Southern Punjab','Public University','Modern Campus'],
    scholarships:'HEC & merit-based scholarships', hostel:'On-campus hostel available' },

  // ── SINDH – KARACHI ──
  114:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'55%+ in Intermediate', entry:'KU Entry Test',
    programs:['BS Sciences','BS Social Sciences','BS Pharmacy','BS Business','LLB','BS IT','Mass Communication','MPhil','PhD'],
    description:'University of Karachi (KU) is Pakistan\'s largest university by enrollment, founded in 1951. It is a premier public institution offering diverse programs across natural sciences, social sciences, pharmacy, and business in the heart of Karachi.',
    highlights:['Pakistan\'s Largest Uni','Public Sector','Founded 1951','70+ Departments'],
    scholarships:'Merit, need-based & government scholarships', hostel:'Separate hostels available' },
  115:{ fee:'Rs. 40–70K/sem', feeNum:55000, merit:'60%+ in FSc', entry:'SSUET Entry Test',
    programs:['BS CS','BS SE','BS EE','BS Telecom','BS Civil Eng','BS Mechanical Eng','BBA'],
    description:'Sir Syed University of Engineering & Technology (SSUET) Karachi is a private engineering university established in 1993, affiliated with the Sir Syed Memorial Society. It is one of Karachi\'s leading engineering institutions.',
    highlights:['Engineering Focus','Sir Syed Heritage','Karachi Campus','Industry Links'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  117:{ fee:'Rs. 80–150K/sem', feeNum:115000, merit:'65%+ in FSc', entry:'Hamdard Entry Test',
    programs:['MBBS','BDS','DPT','Doctor of Pharmacy','BS Eastern Medicine','BS Engineering','BBA'],
    description:'Hamdard University Karachi is a private university founded in 1991 by Hamdard Foundation, known for integrating modern medicine with Eastern/Unani medicine. It operates multiple teaching hospitals and research centers.',
    highlights:['Unani Medicine Pioneer','Teaching Hospitals','Multiple Programs','Research Focus'],
    scholarships:'Hamdard Foundation scholarships', hostel:'On-campus hostel available' },
  118:{ fee:'Rs. 50–80K/sem', feeNum:65000, merit:'80%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BDS','DPT','BS Nursing','Allied Health Sciences'],
    description:'Jinnah Sindh Medical University (JSMU) Karachi, formerly Dow Medical College Karachi campus, is one of Sindh\'s leading public medical universities. It is affiliated with multiple teaching hospitals across Karachi.',
    highlights:['Public Medical','Teaching Hospitals','Karachi Campus','Competitive Merit'],
    scholarships:'Government & merit-based scholarships', hostel:'Separate hostels available' },
  121:{ fee:'Rs. 100–200K/sem', feeNum:150000, merit:'80%+ aggregate (MDCAT)', entry:'MDCAT / Ziauddin Test',
    programs:['MBBS','BDS','Doctor of Pharmacy','DPT','BS Nursing','BS Allied Health','MBA Health Management'],
    description:'Ziauddin University Karachi is one of Pakistan\'s premier private medical universities, established in 1995. Known for world-class medical education and research, it operates multiple state-of-the-art teaching hospitals.',
    highlights:['Premium Medical Uni','State-of-art Hospitals','Research Excellence','International Standards'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  122:{ fee:'Rs. 70–120K/sem', feeNum:95000, merit:'65%+ in Intermediate', entry:'IoBM Entry Test',
    programs:['BBA','MBA','BS Finance','BS Marketing','BS Accounting','BS CS','MPA','Executive MBA'],
    description:'Institute of Business Management (IoBM) Karachi is one of Pakistan\'s top business schools, offering AACSB-accredited programs. Known for strong industry connections and career placement, it is a preferred choice for business education.',
    highlights:['Top Business School','AACSB Accredited','Industry Connections','Career Placement'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  123:{ fee:'Rs. 60–120K/sem', feeNum:90000, merit:'60%+ in Intermediate', entry:'Iqra University Test',
    programs:['BBA','MBA','BS CS','BS SE','BS Engineering','BS Media Studies','BS Education'],
    description:'Iqra University Karachi is a private university established in 1998 with campuses in Karachi, Islamabad, and Peshawar. It is known for business and IT programs with strong industry linkages.',
    highlights:['Multiple Campuses','Business & IT Focus','Industry Links','Modern Facilities'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  124:{ fee:'Rs. 25–50K/sem', feeNum:37000, merit:'60%+ in FSc Pre-Engineering', entry:'DUET Entry Test',
    programs:['BS Civil Eng','BS Electrical Eng','BS Mechanical Eng','BS Industrial Eng','BS CS'],
    description:'Dawood University of Engineering & Technology (DUET) Karachi is a public engineering university established in 1962. One of Karachi\'s oldest engineering institutions, it produces skilled engineers for Pakistan\'s industrial sector.',
    highlights:['Public Engineering Uni','60+ Years Heritage','Karachi Campus','Industry Ties'],
    scholarships:'Government & merit scholarships', hostel:'On-campus hostel available' },

  // ── SINDH – INTERIOR ──
  142:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'55%+ in Intermediate', entry:'Sindh University Test',
    programs:['BS Sciences','BS Arts','BS Commerce','LLB','BS Education','BS IT','Mass Communication','MPhil','PhD'],
    description:'University of Sindh Jamshoro, established in 1947, is one of Pakistan\'s oldest and largest public universities. As the premier institution of Sindh, it serves thousands of students across 83 departments and institutes.',
    highlights:['80+ Years Heritage','Public University','83 Departments','Sindh\'s Premier Uni'],
    scholarships:'Government, merit & need-based scholarships', hostel:'Separate hostels available' },
  143:{ fee:'Rs. 30–60K/sem', feeNum:45000, merit:'75%+ aggregate (MDCAT)', entry:'MDCAT',
    programs:['MBBS','BDS','DPT','BS Nursing','Doctor of Pharmacy','Allied Health'],
    description:'Liaquat University of Medical & Health Sciences (LUMHS) Jamshoro is Sindh\'s largest public medical university, established in 1881. It operates multiple teaching hospitals and is the primary medical institution for interior Sindh.',
    highlights:['140+ Years Heritage','Public Medical','Teaching Hospitals','Interior Sindh'],
    scholarships:'Government & merit-based scholarships', hostel:'Separate hostels available' },
  145:{ fee:'Rs. 80–150K/sem', feeNum:115000, merit:'75%+ aggregate (MDCAT)', entry:'MDCAT / Isra Test',
    programs:['MBBS','BDS','DPT','Doctor of Pharmacy','BS Allied Health'],
    description:'Isra University Hyderabad is a private medical university established in 1997. It operates a modern teaching hospital in Hyderabad and provides quality medical education to students from Sindh and Balochistan.',
    highlights:['Private Medical Uni','Teaching Hospital','Hyderabad Campus','Modern Facilities'],
    scholarships:'Merit & need-based scholarships', hostel:'Separate hostels available' },
  147:{ fee:'Rs. 20–50K/sem', feeNum:35000, merit:'65%+ in Intermediate', entry:'Sukkur IBA Test',
    programs:['BBA','MBA','BS CS','BS SE','BE Civil','BE Electrical','BS Economics','BS Education'],
    description:'Sukkur IBA University is a public university established in 1994 with a strong focus on business and technology education. Known for producing highly employable graduates, it has transformed higher education access in interior Sindh.',
    highlights:['Interior Sindh Leader','Business & Tech','Employability Focus','Public University'],
    scholarships:'Generous merit & need-based scholarships', hostel:'On-campus hostel available' },
  149:{ fee:'Rs. 20–40K/sem', feeNum:30000, merit:'60%+ in FSc Pre-Engineering', entry:'ECAT / QUEST Test',
    programs:['BE Civil Eng','BE Electrical Eng','BE Mechanical Eng','BE Computer Eng','BS CS'],
    description:'Quaid-e-Awam University of Engineering, Science & Technology (QUEST) Nawabshah is a public engineering university in Sindh, established in 1974. It is the premier engineering institution for interior Sindh students.',
    highlights:['Public Engineering','Interior Sindh','ECAT Based Admission','50+ Years Heritage'],
    scholarships:'Government & merit scholarships', hostel:'On-campus hostel available' },

  // ── KPK ──
  159:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'ICU Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS IT','BS Business','MA','MSc','MPhil'],
    description:'Islamia College University (ICU) Peshawar is one of Pakistan\'s most historic institutions, established in 1913 during the British era. It is a cherished symbol of Pashtun culture and academic heritage, offering diverse programs.',
    highlights:['110+ Years Heritage','Historic Institution','Pashtun Heritage','Public University'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  160:{ fee:'Rs. 30–60K/sem', feeNum:45000, merit:'60%+ in FSc (ETEA)', entry:'ETEA',
    programs:['BS Civil Eng','BS Electrical Eng','BS Mechanical Eng','BS Computer Eng','BS CS','BS Industrial Eng'],
    description:'University of Engineering & Technology (UET) Peshawar is KPK\'s premier public engineering university, founded in 1952. It is affiliated with ETEA and produces highly skilled engineers for Pakistan\'s construction and technology sectors.',
    highlights:['KPK\'s Top Engineering','ETEA Based','70+ Years Heritage','Public University'],
    scholarships:'Merit & HEC scholarships', hostel:'Separate hostels available' },
  161:{ fee:'Rs. 50–100K/sem', feeNum:75000, merit:'75%+ aggregate (MDCAT)', entry:'KMU / MDCAT',
    programs:['MBBS','BDS','Doctor of Pharmacy','DPT','BS Nursing','BS Allied Health'],
    description:'Khyber Medical University (KMU) Peshawar is KPK\'s premier public medical university, established in 2007. It regulates and oversees medical education across all of KPK and supervises multiple affiliated medical colleges.',
    highlights:['KPK\'s Top Medical Uni','Regulatory Body','Multiple Affiliates','Modern Facilities'],
    scholarships:'Government & merit-based scholarships', hostel:'Separate hostels available' },
  162:{ fee:'Rs. 40–70K/sem', feeNum:55000, merit:'65%+ in Intermediate', entry:'IMSciences Test',
    programs:['BBA','MBA','BS Economics','BS Media Studies','MPA','Executive MBA'],
    description:'Institute of Management Sciences (IMSciences) Peshawar is a public business school established in 1995, recognized as one of KPK\'s top institutions for business and management education with a strong alumni network.',
    highlights:['KPK\'s Top Business School','Public Sector','Strong Alumni','Career Focused'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  170:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in FSc', entry:'Gomal University Test',
    programs:['BS Agriculture','BS Pharmacy','BS Sciences','BS Arts','BS Education','BS IT','BS Business','DVM','MPhil','PhD'],
    description:'Gomal University DI Khan, established in 1974, is one of KPK\'s largest public universities serving students from DI Khan, Tank, and South KPK regions. It offers diverse programs including agriculture, pharmacy, and sciences.',
    highlights:['Public University','South KPK','Diverse Programs','50+ Years Heritage'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  172:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'50%+ in Intermediate', entry:'UOM Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS IT','BS Education','BS Business','MPhil'],
    description:'University of Malakand (UOM) Chakdara is a public university in Lower Dir, KPK, established in 2001. It provides affordable higher education to students from Malakand Division including Dir, Swat, and Chitral.',
    highlights:['Malakand Division','Public University','Affordable Fees','Mountain Region'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  175:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'50%+ in Intermediate', entry:'HU Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','BS IT','BS Engineering','BS Education','MPhil','PhD'],
    description:'Hazara University Mansehra is a public university established in 2002, serving the Hazara Division of KPK including Mansehra, Abbottabad, Battagram, and Kohistan. It offers affordable higher education in a scenic mountain setting.',
    highlights:['Hazara Division','Public University','Mountain Setting','Affordable Education'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },
  179:{ fee:'Rs. 15–30K/sem', feeNum:22000, merit:'55%+ in Intermediate', entry:'AWKUM Entry Test',
    programs:['BS Sciences','BS Arts','BS Business','BS Engineering','BS Pharmacy','BS IT','BS Education','MPhil','PhD'],
    description:'Abdul Wali Khan University Mardan (AWKUM) is a public university established in 2009, named after the legendary Pashtun leader. It serves as the primary higher education institution for Mardan and Charsadda districts of KPK.',
    highlights:['Mardan Campus','Public University','Named After AWK','Diverse Programs'],
    scholarships:'Merit & need-based scholarships', hostel:'On-campus hostel available' },

  // ── BALOCHISTAN ──
  198:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'50%+ in Intermediate', entry:'UOB Entry Test',
    programs:['BS Sciences','BS Arts','BS Commerce','LLB','BS Engineering','BS IT','BS Social Sciences','MPhil','PhD'],
    description:'University of Balochistan (UOB) Quetta is Balochistan\'s oldest and largest public university, established in 1970. It is the premier institution for higher education in the province, serving students from all across Balochistan.',
    highlights:['Balochistan\'s Oldest Uni','Public Sector','55+ Years Heritage','Quetta Campus'],
    scholarships:'Government, provincial & merit scholarships', hostel:'Separate hostels available' },
  200:{ fee:'Rs. 20–45K/sem', feeNum:32000, merit:'55%+ in FSc', entry:'BUITEMS Entry Test',
    programs:['BS CS','BS SE','BS EE','BS Civil Eng','BBA','MBA','BS Architecture','BS Textile'],
    description:'Balochistan University of IT, Engineering & Management Sciences (BUITEMS) Quetta is Balochistan\'s leading public technology university, established in 2002. It has transformed technical education in the province with modern programs.',
    highlights:['Tech & Engineering Focus','Public University','Modern Programs','Quetta Campus'],
    scholarships:'Merit, provincial & HEC scholarships', hostel:'On-campus hostel available' },

  // ── AJK & GILGIT-BALTISTAN ──
  210:{ fee:'Rs. 20–45K/sem', feeNum:32000, merit:'60%+ in FSc', entry:'MUST Entry Test',
    programs:['BS CS','BS SE','BS EE','BS Civil Eng','BS Telecom','BBA','MBA'],
    description:'Mirpur University of Science & Technology (MUST) is AJK\'s premier public engineering university, established in 1980. It has played a central role in developing a skilled technical workforce in Azad Kashmir.',
    highlights:['AJK\'s Top Engineering','Public University','45+ Years Heritage','Technical Focus'],
    scholarships:'AJK government & merit scholarships', hostel:'On-campus hostel available' },
  211:{ fee:'Rs. 10–25K/sem', feeNum:17000, merit:'50%+ in Intermediate', entry:'UAJK Entry Test',
    programs:['BS Sciences','BS Arts','BS Education','BS IT','BS Business','BS Social Sciences','MPhil','PhD'],
    description:'University of Azad Jammu & Kashmir (UAJK) Muzaffarabad is the state university of AJK, established in 1980. It is the flagship university of Azad Kashmir, offering diverse programs and serving as a center of higher education for the region.',
    highlights:['AJK\'s Flagship Uni','State University','Public Sector','Muzaffarabad Campus'],
    scholarships:'AJK government, merit & need-based scholarships', hostel:'Separate hostels available' },
  217:{ fee:'Rs. 15–35K/sem', feeNum:25000, merit:'55%+ in Intermediate', entry:'KIU Entry Test',
    programs:['BS Sciences','BS Social Sciences','BS IT','BS CS','BS Engineering','BS Education','MPhil','PhD'],
    description:'Karakoram International University (KIU) Gilgit is the only public university in Gilgit-Baltistan, established in 2002. Located amid the world\'s highest mountain ranges, it is a vital center of education and research for the GB region.',
    highlights:['GB\'s Only Public Uni','World\'s Highest Campus','Public Sector','Mountain Research'],
    scholarships:'GB government, AKES & merit scholarships', hostel:'On-campus hostel available' }
};
UNIVERSITIES.forEach(u=>{ if(DATA_UPDATES[u.id]) Object.assign(u, DATA_UPDATES[u.id]); });

// ─── Logo loading: Clearbit HD → favicon fallback → emoji ───
const LOGO_OVERRIDES = {
  'nust.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/a/aa/NUSTuniversitylogo.jpg',
  'lums.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/thumb/3/38/Lahore_University_of_Management_Sciences_Logo.svg/500px-Lahore_University_of_Management_Sciences_Logo.svg.png',
  'uet.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/University_of_Engineering_and_Technology_Lahore_logo.svg/500px-University_of_Engineering_and_Technology_Lahore_logo.svg.png',
  'iba.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/1/1e/Institute_of_Business_Administration%2C_Karachi_%28logo%29.png',
  'comsats.edu.pk':    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/COMSATS_new_logo.jpg/250px-COMSATS_new_logo.jpg',
  'nu.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/National_University_of_Computer_and_Emerging_Sciences_logo.png/250px-National_University_of_Computer_and_Emerging_Sciences_logo.png',
  'qau.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/3/35/Quaid-i-Azam_University_logo.png',
  'giki.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/5/59/GIKI_logo_with_text.png',
  'pieas.edu.pk':      'https://upload.wikimedia.org/wikipedia/en/e/e0/PIEAS_Logo.jpg',
  'neduet.edu.pk':     'https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/NEDUET_logo.svg/500px-NEDUET_logo.svg.png',
  'pu.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/c/c8/University_of_the_Punjab_logo.png',
  'aku.edu':           'https://upload.wikimedia.org/wikipedia/en/6/64/Aga_Khan_University_Logo.png',
  'habib.edu.pk':      'https://upload.wikimedia.org/wikipedia/en/3/38/Habib_University.jpg',
  'au.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/6/61/Air_University_Pakistan_Insignia.png',
  'itu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/d/d9/Information_Technology_University.png',
  'muet.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Mehran_University_of_Engineering_and_Technology_logo.svg/500px-Mehran_University_of_Engineering_and_Technology_logo.svg.png',
  'ucp.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/e/eb/University_of_Central_Punjab_%28logo%29.jpg',
  'szabist.edu.pk':    'https://upload.wikimedia.org/wikipedia/en/f/f9/SZABIST-University-Logo-Blue-Horizontal.png',
  'gcu.edu.pk':        'https://upload.wikimedia.org/wikipedia/commons/f/f5/Government_College_University%2CLogo.png',
  'ist.edu.pk':        'https://upload.wikimedia.org/wikipedia/commons/2/23/Logo_IST.png',
  'fccollege.edu.pk':  'https://upload.wikimedia.org/wikipedia/en/9/97/Forman_Christian_College_logo.png',
  'numl.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/d/d5/National_University_of_Modern_Languages_%28logo%29.jpg',
  'uettaxila.edu.pk':  'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/UET_Taxila_logo.svg/500px-UET_Taxila_logo.svg.png',
  'duhs.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/b/bf/Logo_of_Dow_University_of_Health_Sciences.gif',
  'uhs.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/University_of_Health_Sciences_Lahore_Logo.svg/500px-University_of_Health_Sciences_Lahore_Logo.svg.png',
  'bzu.edu.pk':        'https://upload.wikimedia.org/wikipedia/commons/9/9c/BZU-Multan.png',
  'iiu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/1/1e/International_Islamic_University%2C_Islamabad_%28crest%29.png',
  'uop.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/d/de/University_of_Peshawar_logo.png',
  'nca.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/f/f5/National_College_of_Arts_%28emblem%29.jpg',
  'bahria.edu.pk':     'https://bahria.edu.pk/Content/images/bu_logo.png',
  // 188 basic universities — Wikipedia verified logos
  'aiou.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/8/87/Allama_Iqbal_Open_University_logo.png',
  'vu.edu.pk':         'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/VU_Logo.png/250px-VU_Logo.png',
  'lcwu.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/e/e0/LCWU_Lahore_logo.PNG',
  'kemu.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/4/4f/King_Edward_Medical_University.png',
  'uvas.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/0/0b/UVAS_Lahore.jpg',
  'uaf.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/2/2e/Agriculture_University_Faisalabad_emblem.png',
  'ntu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/e/e4/National_Textile_University_Logo.png',
  'gcuf.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/0/01/Government_College_University_Logo.jpg',
  'uos.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/c/c3/University_of_Sargodha.png',
  'uog.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/c/c4/University_of_Gujrat_Logo.png',
  'uok.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/d/d9/Karachi_University_logo.png',
  'usindh.edu.pk':     'https://upload.wikimedia.org/wikipedia/en/7/7c/University_of_Sindh_%28logo%29.png',
  'lumhs.edu.pk':      'https://upload.wikimedia.org/wikipedia/en/7/7c/Liaquat_University_of_Medical_and_Health_Sciences_%28crest%29.jpg',
  'iba-suk.edu.pk':    'https://upload.wikimedia.org/wikipedia/commons/d/d3/SIBA_Logo.jpg',
  'quest.edu.pk':      'https://upload.wikimedia.org/wikipedia/commons/b/b9/Logo_of_Quaid-e-Awam_university_of_engineering_science_and_technology.jpg',
  'uetpeshawar.edu.pk':'https://upload.wikimedia.org/wikipedia/en/thumb/9/95/University_of_Engineering_and_Technology_Peshawar_logo.svg/250px-University_of_Engineering_and_Technology_Peshawar_logo.svg.png',
  'kmu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/f/f1/KMU_Peshawar.jpg',
  'gu.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/5/57/Gomal_University_logo.png',
  'uom.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/a/a3/University_of_Malakand_%28crest%29.jpg',
  'hu.edu.pk':         'https://upload.wikimedia.org/wikipedia/en/2/28/Hazara_University_logo.jpeg',
  'kust.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/0/06/KUST.png',
  'uob.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/3/30/University_of_Balochistan_logo.jpg',
  'buitms.edu.pk':     'https://upload.wikimedia.org/wikipedia/en/f/fd/BUITEMS_logo.png',
  'must.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/2/2c/Mirpur_University_Of_Science_And_Technology_Logo.png',
  'ajku.edu.pk':       'https://upload.wikimedia.org/wikipedia/en/4/49/University_Of_Azad_Jammu_And_Kashmir_Logo.png',
  'kiu.edu.pk':        'https://upload.wikimedia.org/wikipedia/en/a/a8/Karakoram_International_University_%28logo%29.jpg',
};

function logoSrc(u) {
  if (u.logoUrl) return u.logoUrl;              // custom logo from DB (preferred)
  if (!u.website) return '';
  return LOGO_OVERRIDES[u.website] || `https://www.google.com/s2/favicons?domain=${u.website}&sz=128`;
}

function handleLogoError(img, domain, fallback) {
  img.parentElement.innerHTML = fallback;
}
function checkLogoSize(img, fallback) {
  // If favicon came back tiny (≤20px) replace with emoji — looks far better than a blurry 16px icon
  if (img.naturalWidth <= 20) img.parentElement.innerHTML = fallback;
}

// ─── MERIT MAP: minimum aggregate % for admission ───
const MERIT_MAP = {
  1:85,2:84,3:75,4:82,5:75,6:65,7:60,8:82,9:87,10:72,
  11:55,12:87,13:75,14:65,15:60,16:72,17:60,18:60,19:65,20:65,
  21:65,22:70,23:55,24:72,25:78,26:78,27:55,28:55,29:55,30:60,
  31:62,32:45,33:45,34:65,35:60,36:55,37:62,38:65,39:60,40:82,
  41:62,42:55,43:65,44:55,45:55,
  46:55,47:82,48:84,49:60,50:60,51:62,52:57,53:62,54:55,55:57,
  56:55,57:55,58:60,59:63,60:57,61:55,62:60,63:55,64:62,65:55,
  66:55,67:55,68:55,
  69:55,70:55,71:77,72:82,73:55,74:62,
  75:57,76:55,77:62,78:77,79:55,80:55,
  81:55,82:55,83:55,84:55,85:57,86:77,87:62,88:55,89:60,90:55,
  91:55,92:55,93:62,94:55,95:57,96:55,97:67,98:50,99:50,100:50,
  101:50,102:50,103:62,104:50,105:50,106:50,107:50,108:50,109:50,
  110:50,111:62,112:57,113:55,
  114:55,115:62,116:62,117:65,118:80,119:65,120:60,121:80,122:67,
  123:60,124:62,125:55,126:60,127:60,128:55,129:55,130:55,131:57,
  132:55,133:67,134:57,135:55,136:60,137:55,138:67,139:60,140:55,141:55,
  142:50,143:75,144:50,145:72,146:55,147:62,148:50,149:62,150:50,
  151:72,152:50,153:72,154:50,155:50,156:55,157:50,158:55,
  159:55,160:65,161:75,162:65,163:55,164:62,165:65,166:57,167:57,
  168:57,169:55,170:55,171:57,172:50,173:50,174:50,175:50,176:55,
  177:57,178:50,179:55,180:50,181:57,182:50,183:50,184:50,185:50,
  186:50,187:50,188:50,189:55,190:50,191:50,192:50,193:50,194:57,
  195:57,196:55,197:50,
  198:50,199:72,200:55,201:50,202:50,203:50,204:50,205:57,206:50,
  207:50,208:50,209:57,
  210:62,211:50,212:50,213:55,214:50,215:50,216:50,
  217:57,218:50
};
UNIVERSITIES.forEach(u=>{ if(!u.meritMin) u.meritMin = MERIT_MAP[u.id] || 50; });
