-- Logo URLs for 160+ universities

UPDATE institutions SET logo_url = 'https://ndu.edu.pk/img/ndu-logo.png' WHERE id = 31; -- NDU
UPDATE institutions SET logo_url = 'https://aiou.edu.pk/sites/default/files/aiouLogo_0%20%282%29_0.png' WHERE id = 32; -- AIOU
UPDATE institutions SET logo_url = 'https://vu.edu.pk/img/logo.png' WHERE id = 33; -- VU
UPDATE institutions SET logo_url = 'https://cust.edu.pk/wp-content/uploads/2022/08/LOGO.png' WHERE id = 34; -- CUST
UPDATE institutions SET logo_url = 'https://file.pide.org.pk/uploads/pide-logo-green.png' WHERE id = 38; -- PIDE
UPDATE institutions SET logo_url = 'https://www.szabmu.edu.pk/content/images/header-szabmu.jpg' WHERE id = 40; -- SZABMU
UPDATE institutions SET logo_url = 'https://nutech.edu.pk/imgs/logo.svg' WHERE id = 41; -- NUTECH
UPDATE institutions SET logo_url = 'https://case.edu.pk/wp-content/uploads/2023/05/CASE-Logo@2x.png' WHERE id = 43; -- CASE
UPDATE institutions SET logo_url = 'https://lcwu.edu.pk/templates/shaper_educon/images/presets/preset4/logo.png' WHERE id = 46; -- LCWU
UPDATE institutions SET logo_url = 'https://www.fjmu.edu.pk/wp-content/uploads/2022/09/logo.png' WHERE id = 47; -- FJMU
UPDATE institutions SET logo_url = 'https://kemu.edu.pk/wp-content/uploads/Kemu-logo.png' WHERE id = 48; -- KEMU
UPDATE institutions SET logo_url = 'https://uvas.edu.pk/img/new-theme/new-logo.png' WHERE id = 49; -- UVAS
UPDATE institutions SET logo_url = 'https://kinnaird.edu.pk/wp-content/uploads/2024/02/logo100.png' WHERE id = 50; -- Kinnaird
UPDATE institutions SET logo_url = 'https://umt.edu.pk/images/umt-logo.png' WHERE id = 51; -- UMT
UPDATE institutions SET logo_url = 'https://bnu.edu.pk/portals/TCFLogoTransparent.png' WHERE id = 53; -- BNU
UPDATE institutions SET logo_url = 'https://www.superior.edu.pk/wp-content/uploads/2025/05/Superior-University-Logo.svg' WHERE id = 55; -- Superior
UPDATE institutions SET logo_url = 'https://ue.edu.pk/images/logo.png' WHERE id = 56; -- UOE
UPDATE institutions SET logo_url = 'https://hajvery.edu.pk/images/Logo_Website.png' WHERE id = 57; -- Hajvery
UPDATE institutions SET logo_url = 'https://pifd.edu.pk/n-site/images/logo-white.png' WHERE id = 58; -- PIFD
UPDATE institutions SET logo_url = 'https://lahoreschoolofeconomics.edu.pk/assets/dist/img/logo_old.jpg' WHERE id = 59; -- LSE
UPDATE institutions SET logo_url = 'https://lgu.edu.pk/wp-content/uploads/2024/01/lLAHORE-GARRISON-UNIVERSITY.png' WHERE id = 60; -- LGU
UPDATE institutions SET logo_url = 'https://cdn.prod.website-files.com/66c3a45aed786e5f3c5b22e6/6920312cd99c1dea39bd0fe3_NCBA%26E%20Logo.png' WHERE id = 62; -- NCBA&E
UPDATE institutions SET logo_url = 'https://iac.edu.pk/Untitled-1.png' WHERE id = 65; -- IAC
UPDATE institutions SET logo_url = 'https://www.uaar.edu.pk/images/logo.png' WHERE id = 69; -- PMAS-AAUR
UPDATE institutions SET logo_url = 'https://www.rwu.edu.pk/wp-content/uploads/2024/05/logo-new4-1000x146.png' WHERE id = 73; -- RWU
UPDATE institutions SET logo_url = 'https://hitecuni.edu.pk/Content/img/logo/HitecLogo.svg' WHERE id = 74; -- HITEC
UPDATE institutions SET logo_url = 'https://uaf.edu.pk/MainSite/img/logo.png' WHERE id = 75; -- UAF
UPDATE institutions SET logo_url = 'https://gcuf.edu.pk/wp-content/uploads/2024/12/logo-3.png' WHERE id = 76; -- GCUF
UPDATE institutions SET logo_url = 'https://ntu.edu.pk/assets/img/logo.png' WHERE id = 77; -- NTU
UPDATE institutions SET logo_url = 'https://tuf.edu.pk/Main/frontend/images/logo.png' WHERE id = 80; -- UOF
UPDATE institutions SET logo_url = 'https://iub.edu.pk/uploads/images/nav/iub-100-years.png' WHERE id = 81; -- IUB
UPDATE institutions SET logo_url = 'https://gscwu.edu.pk//images/gscwu-logo.png' WHERE id = 82; -- GSCWU
UPDATE institutions SET logo_url = 'https://cuvas.edu.pk/img/Responsivs/logo-responsive.png' WHERE id = 83; -- CUVAS
UPDATE institutions SET logo_url = 'https://wum.edu.pk/wp-content/uploads/2022/07/logo.png' WHERE id = 84; -- WUM
UPDATE institutions SET logo_url = 'https://usp.edu.pk/wp-content/uploads/2026/01/USP-Multan-Pakistan-Logo.png' WHERE id = 85; -- USP
UPDATE institutions SET logo_url = 'https://nmu.edu.pk/wp-content/uploads/2021/09/logo.webp' WHERE id = 86; -- NMU
UPDATE institutions SET logo_url = 'https://mnsuam.edu.pk/images/logos/logo-mnsuam.png' WHERE id = 88; -- MNS-UA
UPDATE institutions SET logo_url = 'https://mnsuet.edu.pk/wp-content/uploads/2026/04/new_logo_mnsuet_2-removebg-preview.png' WHERE id = 89; -- MNS-UET
UPDATE institutions SET logo_url = 'https://tum.edu.pk/images/logo.png?v2' WHERE id = 90; -- Times
UPDATE institutions SET logo_url = 'https://gift.edu.pk/images/GIFT-logo.png' WHERE id = 93; -- GIFT
UPDATE institutions SET logo_url = 'https://template.uog.edu.pk/uog/upload/events/logo_e.png' WHERE id = 94; -- UOG
UPDATE institutions SET logo_url = 'https://uskt.edu.pk/hybridLogo.webp' WHERE id = 95; -- USKT
UPDATE institutions SET logo_url = 'https://gcwus.edu.pk/wp-content/themes/gcwus/images/logo.png' WHERE id = 96; -- GCWUS
UPDATE institutions SET logo_url = 'https://namal.edu.pk/uploads/logo22869383.png' WHERE id = 97; -- Namal
UPDATE institutions SET logo_url = 'https://kfueit.edu.pk/uploads/4/ueit-logo-r.png' WHERE id = 103; -- KFUEIT
UPDATE institutions SET logo_url = 'https://ul.edu.pk/storage/career/files/UL-Main-Logo-47ffb.png' WHERE id = 106; -- UOLayyah
UPDATE institutions SET logo_url = 'https://bgnu.edu.pk/assets/img/logo/logo 2.png' WHERE id = 110; -- BGNU
UPDATE institutions SET logo_url = 'https://ptut.edu.pk/wp-content/uploads/2025/03/PTUT-Logo.jpg#4497' WHERE id = 111; -- PTUTT
UPDATE institutions SET logo_url = 'https://uow.edu.pk/Content/theme/images/MASTER-LOGO.jpg' WHERE id = 112; -- UOW
UPDATE institutions SET logo_url = 'https://uorm.edu.pk/wp-content/uploads/2021/07/government-of-punjab-logo-1E1A7AB42A-seeklogo.com_-150x150.png' WHERE id = 113; -- PUTR
UPDATE institutions SET logo_url = 'https://uok.edu.pk/images/logo.png' WHERE id = 114; -- UOK
UPDATE institutions SET logo_url = 'https://www.ssuet.edu.pk/wp-content/uploads/SSUET-Official-Logo.webp' WHERE id = 115; -- SSUET
UPDATE institutions SET logo_url = 'https://cdn-fobig.nitrocdn.com/XOPvWCmkDWeqniZzwWrOraENxFtSCcbb/assets/images/optimized/rev-6e04ce2/www.hamdard.edu.pk/wp-content/uploads/2022/06/Hamdard-University-Logo-W-01-1-e1778140574186.png' WHERE id = 117; -- Hamdard
UPDATE institutions SET logo_url = 'https://jsmu.edu.pk/assets/images/logo.png' WHERE id = 118; -- JSMU
UPDATE institutions SET logo_url = 'https://baqai.edu.pk/wp-content/uploads/2024/02/images-1.png' WHERE id = 119; -- Baqai
UPDATE institutions SET logo_url = 'https://www.dsu.edu.pk/wp-content/uploads/2024/07/suffa_logo.png' WHERE id = 120; -- DSU
UPDATE institutions SET logo_url = 'https://zu.edu.pk/wp-content/uploads/2024/11/international-collaboration-logos-29-1-267x300-1.webp' WHERE id = 121; -- Ziauddin
UPDATE institutions SET logo_url = 'https://iobm.edu.pk/wp-content/uploads/2025/02/30-Years-logo-1.png' WHERE id = 122; -- IoBM
UPDATE institutions SET logo_url = 'https://iqra.edu.pk/wp-content/uploads/2025/08/LOGO-IU-01-2048x495-1.png' WHERE id = 123; -- Iqra
UPDATE institutions SET logo_url = 'https://res.cloudinary.com/df6wqygko/image/upload/f_webp/v1781879228/ic299fl8tbe3ohakr6zu.png' WHERE id = 125; -- Greenwich
UPDATE institutions SET logo_url = 'https://kiet.edu.pk/storage/elementor/thumbs/New-Logo-1-1-ricszy16ozed9qsmacxj4t6hd87dw17wzkv3sb1deo.webp' WHERE id = 127; -- KIET
UPDATE institutions SET logo_url = 'https://www.smiu.edu.pk/themes/smiu/images/logo_smiu.png' WHERE id = 128; -- SMIU
UPDATE institutions SET logo_url = 'https://www.juw.edu.pk/resource/uploads/2019/09/logo.png' WHERE id = 129; -- JUW
UPDATE institutions SET logo_url = 'https://dadabhoy.edu.pk/wp-content/uploads/2024/11/dihe-logo-right-side1111-e1733134770882.png' WHERE id = 130; -- Dadabhoy
UPDATE institutions SET logo_url = 'https://indus.edu.pk/images/logo-img.png' WHERE id = 132; -- Indus
UPDATE institutions SET logo_url = 'https://www.ksbl.edu.pk/wp-content/uploads/2022/02/ksbl-menu-logo.png' WHERE id = 133; -- KSBL
UPDATE institutions SET logo_url = 'https://shu.edu.pk/wp-content/uploads/shu-main-logo.svg' WHERE id = 134; -- SHU
UPDATE institutions SET logo_url = 'https://sbbcu.edu.pk/images/logo.jpg' WHERE id = 135; -- SBBCU
UPDATE institutions SET logo_url = 'https://newports.edu.pk/wp-content/uploads/2024/02/Newports-Logo-1024x274.png' WHERE id = 137; -- Newports
UPDATE institutions SET logo_url = 'https://kinpoe.edu.pk/images/logo.gif' WHERE id = 139; -- KINPOE
UPDATE institutions SET logo_url = 'https://maliruniversity.edu.pk/wp-content/uploads/2025/11/pma-logo.png' WHERE id = 140; -- Malir
UPDATE institutions SET logo_url = 'https://bbsul.edu.pk/assets_doc/images/logo-BBSUL.png' WHERE id = 141; -- BBSU
UPDATE institutions SET logo_url = 'https://usindh.edu.pk/images/usindh/logo.png' WHERE id = 142; -- USindh
UPDATE institutions SET logo_url = 'https://lumhs.edu.pk/images/logo-w.png' WHERE id = 143; -- LUMHS
UPDATE institutions SET logo_url = 'https://gcuh.edu.pk/images/logo2.png' WHERE id = 144; -- GCUH
UPDATE institutions SET logo_url = 'https://israuniversity.edu.pk/wp-content/uploads/2015/03/logowhite1.png' WHERE id = 145; -- Isra
UPDATE institutions SET logo_url = 'https://sau.edu.pk/assets/logo.png?v=2' WHERE id = 146; -- SAU
UPDATE institutions SET logo_url = 'https://iba-suk.edu.pk/Content/assets/img/logo-white.png' WHERE id = 147; -- SIBAUK
UPDATE institutions SET logo_url = 'https://salu.edu.pk/images/logo.png' WHERE id = 148; -- SALU
UPDATE institutions SET logo_url = 'https://quest.edu.pk/static/images/logo/logo-color-detailed.png' WHERE id = 149; -- QUEST
UPDATE institutions SET logo_url = 'https://sbbu.edu.pk/images/jiu_logo.jpg' WHERE id = 150; -- SBBU
UPDATE institutions SET logo_url = 'https://pumhs.edu.pk/assets/images/logo.gif' WHERE id = 151; -- PUMHS
UPDATE institutions SET logo_url = 'https://sbbuvas.edu.pk/images/sbbuvaslogo.png' WHERE id = 152; -- SBBUVS
UPDATE institutions SET logo_url = 'https://saus.edu.pk/wp-content/uploads/2024/08/cropped-cropped-Shaikh-Ayaz-Uni-Logo-2.jpg' WHERE id = 155; -- SAYUni
UPDATE institutions SET logo_url = 'https://aror.edu.pk/wp-content/uploads/2024/01/logo-for-website-01.jpg' WHERE id = 156; -- Aror
UPDATE institutions SET logo_url = 'https://www.uetpeshawar.edu.pk/wp-content/uploads/2024/04/UET-Logo.png' WHERE id = 160; -- UETPESHAWAR
UPDATE institutions SET logo_url = 'https://kmu.edu.pk/themes/kmu2020/assets/images/KMU-Logo.png' WHERE id = 161; -- KMU
UPDATE institutions SET logo_url = 'https://imsciences.edu.pk/wp-content/uploads/2024/10/logo-1-final.png' WHERE id = 162; -- IMSciences
UPDATE institutions SET logo_url = 'https://cecos.edu.pk/wp-content/uploads/2023/07/CECOS-Logo.png' WHERE id = 164; -- CECOS
UPDATE institutions SET logo_url = 'https://cityuniversity.edu.pk/wp-content/uploads/2021/06/cusit-logo-white-300x62.png' WHERE id = 167; -- CUI-KPK
UPDATE institutions SET logo_url = 'https://qurtuba.edu.pk/U_assets/images/university.png' WHERE id = 169; -- Qurtuba
UPDATE institutions SET logo_url = 'https://aup.edu.pk/assets/img/uap-logo.png' WHERE id = 171; -- UAPESHAWAR
UPDATE institutions SET logo_url = 'https://uswat.edu.pk/wp-content/uploads/2024/03/logo-uswat-70x70.png' WHERE id = 173; -- USWAT
UPDATE institutions SET logo_url = 'https://aust.edu.pk/wp-content/uploads/2025/07/Logo1-1.png' WHERE id = 176; -- AUST
UPDATE institutions SET logo_url = 'https://uoh.edu.pk/assets/images/logo.png' WHERE id = 178; -- UOH
UPDATE institutions SET logo_url = 'https://awkum.edu.pk/wp-content/uploads/2020/06/header-style-mobile-logo-regular.png' WHERE id = 179; -- AWKUM
UPDATE institutions SET logo_url = 'https://wumardan.edu.pk/wp-content/uploads/2023/09/logo-2.png' WHERE id = 180; -- WUM-KPK
UPDATE institutions SET logo_url = 'https://www.uetmardan.edu.pk/uetm/new/img/logo/uet-logo14.png' WHERE id = 181; -- UETMARDAN
UPDATE institutions SET logo_url = 'https://bkuc.edu.pk/media/1/1768213997.png' WHERE id = 182; -- BKU
UPDATE institutions SET logo_url = 'https://ustb.edu.pk/assets/img/logo.png' WHERE id = 183; -- USTB
UPDATE institutions SET logo_url = 'https://kkkuk.edu.pk/wp-content/uploads/2023/07/KKUK-LOGO-80.png' WHERE id = 185; -- KKKUK
UPDATE institutions SET logo_url = 'https://www.ubuner.edu.pk/uobv2/wp-content/uploads/2014/10/logo-3.png' WHERE id = 187; -- UBUNER
UPDATE institutions SET logo_url = 'https://paf-iast.edu.pk/wp-content/uploads/2024/06/PAFIASTLOGOPNGFinal.png' WHERE id = 194; -- PAAAS
UPDATE institutions SET logo_url = 'https://northern.edu.pk/assets/img/all-img/logo.webp' WHERE id = 196; -- NUN
UPDATE institutions SET logo_url = 'https://uad.edu.pk/images/UAD_Logo1.png' WHERE id = 197; -- UADIK
UPDATE institutions SET logo_url = 'https://bumhs.edu.pk/images/bumhs logo2.png' WHERE id = 199; -- BUMHS
UPDATE institutions SET logo_url = 'https://buitms.edu.pk/Content/img/logo101.png' WHERE id = 200; -- BUITEMS
UPDATE institutions SET logo_url = 'https://www.sbkwu.edu.pk/wp-content/uploads/2024/10/logo-transparent.png' WHERE id = 201; -- SBKWU
UPDATE institutions SET logo_url = 'https://uot.edu.pk/img/uotlogo-sm.png' WHERE id = 202; -- UOTUR
UPDATE institutions SET logo_url = 'https://luawms.edu.pk/images/luawms-website-logo.png' WHERE id = 206; -- LUAWMS
UPDATE institutions SET logo_url = 'https://www.alhamd.edu.pk/wp-content/uploads/2021/12/site-logo.png' WHERE id = 209; -- AHIU
UPDATE institutions SET logo_url = 'https://uajk.edu.pk/wp-content/uploads/2023/03/ajk3sulogo2.png' WHERE id = 211; -- UAJK
UPDATE institutions SET logo_url = 'https://upr.edu.pk/images/logo.png' WHERE id = 212; -- UOPOONCH
UPDATE institutions SET logo_url = 'https://wuajk.edu.pk/public/front/assets/images/logofinal.png' WHERE id = 215; -- WUAJK
UPDATE institutions SET logo_url = 'https://kiu.edu.pk/images/logo.png' WHERE id = 217; -- KIU
UPDATE institutions SET logo_url = 'https://ubas.edu.pk/wp-content/uploads/2025/01/UBAS-Logo.png' WHERE id = 222; -- UBAS
UPDATE institutions SET logo_url = 'https://kasbit.edu.pk/kasbitcontentstorage/2022/12/kasbitlogo-1.png' WHERE id = 224; -- KASBIT
UPDATE institutions SET logo_url = 'https://tip.edu.pk/wp-content/uploads/2024/04/Artboard-1-copy-3.png' WHERE id = 225; -- TIP
UPDATE institutions SET logo_url = 'https://preston.edu.pk/assets/images/logo.png' WHERE id = 226; -- PRESTON
UPDATE institutions SET logo_url = 'https://giu.edu.pk/front/images/new-giu/homepage/logo.png' WHERE id = 227; -- GIU
UPDATE institutions SET logo_url = 'https://ueas.edu.pk/./assets/images/UEAS_LOGO.jpg' WHERE id = 228; -- UEAS
UPDATE institutions SET logo_url = 'https://imperial.edu.pk/wp-content/uploads/2023/11/Logo-New-Imperial-College-500x88.png' WHERE id = 229; -- IMPERIAL
UPDATE institutions SET logo_url = 'https://uchs.edu.pk/wp-content/uploads/2022/10/uni-logo-e1665662555936.png' WHERE id = 230; -- UCHS
UPDATE institutions SET logo_url = 'https://gims.edu.pk/images/logo1.png' WHERE id = 232; -- GIMS
UPDATE institutions SET logo_url = 'https://sbbusba.edu.pk/images/logo.png' WHERE id = 233; -- SBBU-SBA
UPDATE institutions SET logo_url = 'https://uchenab.edu.pk/wp-content/uploads/2022/01/UOC-logo-white-final-300x95.webp' WHERE id = 234; -- UCHENAB
UPDATE institutions SET logo_url = 'https://uit.edu/assets/images/LogoUIT(White).png' WHERE id = 235; -- UIT
UPDATE institutions SET logo_url = 'https://aie.edu.pk/wp-content/uploads/2024/12/cropped-AIE-logo-1-e1724399633681.svg' WHERE id = 236; -- AIE
UPDATE institutions SET logo_url = 'https://commecsinstitute.edu.pk/wp-content/uploads/2023/01/Logo-full.png' WHERE id = 237; -- CIBES
UPDATE institutions SET logo_url = 'https://mite.edu.pk/wp-content/uploads/elementor/thumbs/New-Cambridge-Logo-pppn59znq7k8qgdeo0855agubwk5r3faicjevnqrcw.png' WHERE id = 238; -- MITE
UPDATE institutions SET logo_url = 'https://nhu.edu.pk/wp-content/uploads/2022/01/logo-2.png' WHERE id = 239; -- NHU
UPDATE institutions SET logo_url = 'https://szabul.edu.pk/img/logo2.png' WHERE id = 240; -- SZABUL
UPDATE institutions SET logo_url = 'https://sohailuniversity.edu.pk/wp-content/uploads/2021/03/Sohailuniversity-New-Logo.png' WHERE id = 241; -- SOHAIL
UPDATE institutions SET logo_url = 'https://agu.edu.pk/wp-content/uploads/2026/06/Landscape-Logo-02-1-scaled.webp' WHERE id = 242; -- AGU
UPDATE institutions SET logo_url = 'https://alkawthar.edu.pk/media/images/inline_logo.original.png' WHERE id = 244; -- ALKAWTHAR
UPDATE institutions SET logo_url = 'https://bbsutsd.edu.pk/img/logo/bbsutsd_logo.png' WHERE id = 245; -- BBSUTSD
UPDATE institutions SET logo_url = 'https://rlku.edu.pk/images/rlkuname.png' WHERE id = 247; -- RLKU
UPDATE institutions SET logo_url = 'https://muk.edu.pk/wp-content/uploads/2021/08/logo.png' WHERE id = 250; -- MUK
UPDATE institutions SET logo_url = 'https://list.edu.pk/wp-content/uploads/2024/08/Logo-1-1024x196.png' WHERE id = 251; -- LIST
UPDATE institutions SET logo_url = 'https://ums.edu.pk/images/home/logo.png' WHERE id = 253; -- UMS
UPDATE institutions SET logo_url = 'https://simat.edu.pk/wp-content/uploads/2024/09/cropped-Recognized-by-HEC-2.png' WHERE id = 254; -- SIMAT
UPDATE institutions SET logo_url = 'https://dmiu.edu.pk/wp-content/uploads/2025/10/Logo-3-1.png' WHERE id = 256; -- DMIU
UPDATE institutions SET logo_url = 'https://mypgi.edu.pk/wp-content/uploads/2025/11/PGI-Logo-lite.png' WHERE id = 257; -- MYPGI
UPDATE institutions SET logo_url = 'https://akii.edu.pk/wp-content/uploads/2024/03/logo-150x150.png' WHERE id = 258; -- AKII
UPDATE institutions SET logo_url = 'https://uoas.edu.pk/wp-content/uploads/2024/05/UOAS-Logo-white-400-290x58.png' WHERE id = 259; -- UOAS
UPDATE institutions SET logo_url = 'https://hands-ids.edu.pk/site/wp-content/uploads/2024/06/logo__five.svg' WHERE id = 260; -- HANDS-IDS
UPDATE institutions SET logo_url = 'https://sbbdewanuniversity.edu.pk/./images/logo.png' WHERE id = 262; -- SBBDEWANUNIVERSITY
UPDATE institutions SET logo_url = 'https://isu.edu.pk/images/logo.png' WHERE id = 263; -- ISU
UPDATE institutions SET logo_url = 'https://sbu.edu.pk/wp-content/uploads/2025/09/logo.png' WHERE id = 264; -- SBU
UPDATE institutions SET logo_url = 'https://ibitpu.edu.pk/images/ibit.png' WHERE id = 265; -- IBITPU
UPDATE institutions SET logo_url = 'https://www.isp.edu.pk/wp-content/uploads/2023/11/Logo-400x93.png' WHERE id = 266; -- ISP
UPDATE institutions SET logo_url = 'https://thekmu.edu.pk/wp-content/uploads/2025/03/KMU-09.png' WHERE id = 270; -- KMU-KHI
UPDATE institutions SET logo_url = 'https://mcut.edu.pk/storage/career/files/Logo-MCUT.png' WHERE id = 271; -- MCKRUT
UPDATE institutions SET logo_url = 'https://uotnowshera.edu.pk/wp-content/uploads/2023/05/UOT-Logo-3-1300x330.png' WHERE id = 275; -- SAPSUT
UPDATE institutions SET logo_url = 'https://cdn-ddgcg.nitrocdn.com/tPHCDeyPoQOoksyqyUzkKEzCgBCGthiv/assets/images/optimized/rev-3c5febd/habib.edu.pk/videos/images/HU-Logo-New-Header.svg' WHERE id = 13; -- Habib University
UPDATE institutions SET logo_url = 'https://gcu.edu.pk/components/assets/img/gcu-logo.png' WHERE id = 20; -- GCU Lahore
